refactor: 활동 그룹 목록을 가장 최신에 생성된 순으로 정렬되도록 변경 완료
kgu-clab/clab-platforms-server pull request #551
Opened 2024-09-12 14:48 UTC by SongJaeHoonn

## Summary

> #549 

`나의 활동 목록 조회`, `활동 상태별 조회`, `내가 지원한 활동 목록 조회` api 의 응답인 활동 그룹 목록의 정렬을 아래와 같이 변경했습니다.
- 정렬 기준 : `createdAt`
- 정렬 방향 : `desc` 
 
## Tasks

- 활동 그룹 목록을 반환하는 api들의 응답값을 `createdAt` 기준 `desc` 방향으로 정렬

## ETC

수정 전과 수정 후의 response 값을 기록했었는데, 테스트했던 response 값이 길어 Screenshot이 아닌 텍스트 형식으로 기록했습니다.

## Screenshot

- 내가 지원한 활동 목록 조회 (수정 전)
```json
{
  "success": true,
  "data": {
    "currentPage": 0,
    "hasPrevious": false,
    "hasNext": false,
    "totalPages": 1,
    "totalItems": 2,
    "take": 2,
    "items": [
      {
        "id": 6,
        "name": "게임 스터디",
        "content": "게임 스터디",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "202014941",
            "name": "송재훈"
          },
          {
            "id": "202500001",
            "name": "설윤"
          }
        ],
        "participantCount": 5,
        "weeklyActivityCount": 1,
        "createdAt": "2024-09-06T14:11:09.312321"
      },
      {
        "id": 7,
        "name": "test",
        "content": "test",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "leader",
            "name": "리더"
          }
        ],
        "participantCount": 1,
        "weeklyActivityCount": 0,
        "createdAt": "2024-09-07T12:36:44.223115"
      }
    ]
  }
}
```

- 내가 지원한 활동 목록 조회 (수정 후)
```json
{
  "success": true,
  "data": {
    "currentPage": 0,
    "hasPrevious": false,
    "hasNext": false,
    "totalPages": 1,
    "totalItems": 2,
    "take": 2,
    "items": [
      {
        "id": 7,
        "name": "test",
        "content": "test",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "superuser",
            "name": "관리자"
          }
        ],
        "participantCount": 2,
        "weeklyActivityCount": 0,
        "createdAt": "2024-09-07T12:36:44.223115"
      },
      {
        "id": 6,
        "name": "게임 스터디",
        "content": "게임 스터디",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "202014941",
            "name": "송재훈"
          },
          {
            "id": "202500001",
            "name": "설윤"
          }
        ],
        "participantCount": 5,
        "weeklyActivityCount": 1,
        "createdAt": "2024-09-06T14:11:09.312321"
      }
    ]
  }
}
```
---

- 나의 활동 목록 조회 (수정 전)
```json
{
  "success": true,
  "data": {
    "currentPage": 0,
    "hasPrevious": false,
    "hasNext": false,
    "totalPages": 1,
    "totalItems": 2,
    "take": 2,
    "items": [
      {
        "id": 6,
        "name": "게임 스터디",
        "content": "게임 스터디",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "202014941",
            "name": "송재훈"
          },
          {
            "id": "202500001",
            "name": "설윤"
          }
        ],
        "participantCount": 5,
        "weeklyActivityCount": 1,
        "createdAt": "2024-09-06T14:11:09.312321"
      },
      {
        "id": 7,
        "name": "test",
        "content": "test",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "leader",
            "name": "리더"
          }
        ],
        "participantCount": 2,
        "weeklyActivityCount": 0,
        "createdAt": "2024-09-07T12:36:44.223115"
      }
    ]
  }
}
```

- 나의 활동 목록 조회 (수정 후)
```json
{
  "success": true,
  "data": {
    "currentPage": 0,
    "hasPrevious": false,
    "hasNext": false,
    "totalPages": 1,
    "totalItems": 3,
    "take": 3,
    "items": [
      {
        "id": 11,
        "name": "러브 스터디",
        "content": "러브 스터디",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "202500001",
            "name": "설윤"
          }
        ],
        "participantCount": 1,
        "weeklyActivityCount": 0,
        "createdAt": "2024-09-12T21:39:27.817431"
      },
      {
        "id": 7,
        "name": "test",
        "content": "test",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "leader",
            "name": "리더"
          }
        ],
        "participantCount": 2,
        "weeklyActivityCount": 0,
        "createdAt": "2024-09-07T12:36:44.223115"
      },
      {
        "id": 6,
        "name": "게임 스터디",
        "content": "게임 스터디",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "202014941",
            "name": "송재훈"
          },
          {
            "id": "202500001",
            "name": "설윤"
          }
        ],
        "participantCount": 5,
        "weeklyActivityCount": 1,
        "createdAt": "2024-09-06T14:11:09.312321"
      }
    ]
  }
}
```
---

- 활동 상태별 조회 (수정 전)
```json
{
  "success": true,
  "data": {
    "currentPage": 0,
    "hasPrevious": false,
    "hasNext": false,
    "totalPages": 1,
    "totalItems": 3,
    "take": 3,
    "items": [
      {
        "id": 4,
        "name": "2024-1 신입생 대상 C언어 스터디",
        "content": "2024-1 신입생 대상 C언어 스터디",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "leader",
            "name": "리더"
          },
          {
            "id": "201610000",
            "name": "김민정"
          }
        ],
        "participantCount": 4,
        "weeklyActivityCount": 1,
        "createdAt": "2024-08-25T23:54:34.881528"
      },
      {
        "id": 8,
        "name": "test2",
        "content": "test2",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "leader",
            "name": "리더"
          }
        ],
        "participantCount": 1,
        "weeklyActivityCount": 0,
        "createdAt": "2024-09-07T12:36:52.529044"
      },
      {
        "id": 10,
        "name": "test4",
        "content": "test4",
        "category": "STUDY",
        "subject": "1학년 이상",
        "imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
        "leaders": [
          {
            "id": "leader",
            "name": "리더"
          }
        ],
        "participantCount": 1,
        "weeklyActivityCount": 0,
        "createdAt": "2024-09-07T12:37:07.080174"
      }
    ]
  }
}
```

- 활동 상태별 조회 (수정 후)
```json
{
  "suc [...]

2024-09-12 15:15 UTC, mingmingmon requested changes

2024-09-12 15:15 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
> -        Pageable pageable = pageableUtils.createPageable(page, size, sortBy, sortDirection, ActivityGroupStatusResponseDto.class);
동적 페이지네이션에 필요한 요소들은 다양한 정렬기준으로 볼 수 있도록 확장성을 고려해 남겨두고 있었어요. 

이번 작업에서 활동 그룹 목록의 디폴트 정렬기준을 생성된 순서로 수정해야 한다면, 'sortDirection'의 `defaultValue`를 `desc`로 수정하는 방향은 어떠실까요?

그러면 현재는 `asc`라서 
```
2023-01-01 10:00:00
2023-01-01 12:00:00
2023-01-02 09:00:00
``` 
처럼 정렬되는 것이 `desc`로 수정하면 최신순으로 바뀔 수 있을 것 같아요.

2024-09-12 15:23 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
> -        Pageable pageable = pageableUtils.createPageable(page, size, sortBy, sortDirection, ActivityGroupStatusResponseDto.class);
피드백 해주셔서 감사합니다!!

다만 해당 api에서 사용하는 `getActivityGroupsByStatus()`메서드는 `activityGroupRepository.findActivityGroupsByStatus(status, pageable);`로 `ActivityGroup` 리스트를 조회하고 있어요.
현재 `findActivityGroupsByStatus`는 JPA의 쿼리 메서드를 사용하는 것이 아닌 QueryDSL을 통해 데이터 조회와 페이지네이션을 하고 있는데, 제가 삭제한 `sortBy`와 `sortDirection`이 사용되고 있지 않아 과감하게 삭제하게 되었습니다.

따라서 `asc`를 `desc`로만 수정하면 정렬이 진행되지 않기 때문에 `findActivityGroupsByStatus()`에 복잡한 정렬 로직을 직접 구현해야 했기에, 해당 api가 아닌 다른 활동 목록 조회 메서드에서는 `sort`를 사용하고 있지 않았기에 `sort`와 `sortDirection`을 삭제하는 방향으로 통일하게 되었습니다.

2024-09-12 15:43 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
> -        Pageable pageable = pageableUtils.createPageable(page, size, sortBy, sortDirection, ActivityGroupStatusResponseDto.class);
참고로 아래는 수정 이전에 `PagedResponseDto` 생성 시 사용되던 코드입니다.

```java
public PagedResponseDto(List<T> ts, int totalItems, Pageable pageable) {
    this.currentPage = pageable.getPageNumber();
    this.hasPrevious = pageable.getPageNumber() > 0;
    this.hasNext = pageable.getOffset() + pageable.getPageSize() < totalItems;
    this.totalPages = (totalItems != 0) ? (int) Math.ceil((double) totalItems / pageable.getPageSize()) : 0;
    this.totalItems = totalItems;
    this.take = ts.size();
    this.items = applySortingIfNecessary(ts, pageable.getSort());
}

private List<T> applySortingIfNecessary(List<T> items, Sort sort) {
    if (sort.isSorted()) {
        return sortItems(items, sort);
    }
    return items;
}

private List<T> sortItems(List<T> items, Sort sort) {
    Comparator<T> comparator = sort.stream()
            .map(order -> {
                Comparator<T> itemComparator = Comparator.comparing(
                        item -> {
                            try {
                                return (Comparable) extractFieldValue(item, order.getProperty());
                            } catch (InvalidColumnException e) {
                                throw new RuntimeException(e);
                            }
                        }
                );
                return order.isAscending() ? itemComparator : itemComparator.reversed();
            })
            .reduce(Comparator::thenComparing)
            .orElseThrow(IllegalArgumentException::new);

    return items.stream()
            .sorted(comparator)
            .toList();
}

private Object extractFieldValue(T item, String fieldName) throws InvalidColumnException {
    try {
        var field = item.getClass().getDeclaredField(fieldName);
        field.setAccessible(true);
        return field.get(item);
    } catch (NoSuchFieldException | IllegalAccessException e) {
        throw new InvalidColumnException("잘못된 필드 이름: " + fieldName);
    }
}
```

2024-09-12 15:45 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
> -        Pageable pageable = pageableUtils.createPageable(page, size, sortBy, sortDirection, ActivityGroupStatusResponseDto.class);
develop 브랜치에서 확인해보았는데, 실제로 Controller에서 전달받은 `pageable`이 사용되고 있지 않고 있네요.

해당 메소드가 활동 1차 QA 과정에서 새로 추가된 메소드인 것 같은데, @limehee 님이 피드백 주신 내용처럼 일관된 페이지네이션 정책을 위해서 `pageable`이 사용할 수 있도록 수정해야 될 것 같아요. 

그렇다면 자연스럽게 페이지네이션이 적용되는 다른 Controller 메소드들과 동일하게 페이지네이션 요소들로 유동적인 작업을 유지할 수 있을 것 같아요.

2024-09-12 15:51 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
> -        Pageable pageable = pageableUtils.createPageable(page, size, sortBy, sortDirection, ActivityGroupStatusResponseDto.class);
`PagedResponseDto`에서 따로 정렬이 진행되고 있었군요. 단순히 DAO에서 페이지네이션 시에 정렬이 되는것으로만 생각했었네요. 바로 잡아 주셔서 감사합니다! 잘못 생각하고 있었네요

2024-09-12 15:54 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
> -            @RequestParam(name = "sortDirection", defaultValue = "asc") List<String> sortDirection
정렬이 옳게 된 방식으로 적용이 되고 있다는 사실을 몰랐었네요. 그렇다면 해당 api에서 `defaultValue`값을 `asc`로 하지 않고 `desc`로만 변경해도 최신 순으로 목록을 보여주는 것에 대해서는 비용이 발생하지 않으니 이게 더 좋은 방법일 것 같네요!

2024-09-12 15:54 UTC, mingmingmon commented
빠르게 이야기가 오고 가서, 여기저기 답글을 달면 정신이 없을 것 같아 저도 제 의견 한 코멘트로 정리할게요!
@limehee 님이 언급해주신 유연성과 통일성에 동의하면서 페이지네이션 요소의 삭제보다 sorting 방식을 수정하는 방향을 제안 드렸던 거에요. 

그러나 제가 처음 제안 드렸던 서버측에서 강제적으로 sorting 방식을 asc -> desc로 수정하는 것보다는 클라이언트 측에서 요청 시 적절한 정렬방향을 담아서 요청해주시면 좋을 것 같습니다. 

이렇게 QA나 사용자 피드백으로 요구사항이 바뀔 때마다 정렬 방식을 서버에서 매번 바꾸지 않고, 유연하게 대처하기 위해 만든 것이 "동적 페이지네이션" 기능이었기 때문이에요.

동적 페이지네이션을 제가 작업해놓고, 기능의 궁극적인 쓰임새를 망각하고 있었는데, 이렇게 다시 정리할 수 있게 되었네요. 👍👍

2024-09-12 16:06 UTC, SWARVY commented on src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
> -            @RequestParam(name = "sortDirection", defaultValue = "asc") List<String> sortDirection
프론트엔드 입장에서도 따로 명시하지 않으면 `desc`로 처리하여 최신 데이터를 보내주는게 더 용이할 것으로 보입니다 ~

2024-09-13 00:28 UTC, limehee approved these changes

2024-09-13 07:13 UTC, Jeong-Ag commented on src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
> -            @RequestParam(name = "sortDirection", defaultValue = "asc") List<String> sortDirection
의논한 내용 모두 확인했습니다~

2024-09-13 08:08 UTC, mingmingmon approved these changes

2024-09-13 14:41 UTC, merged