refactor: 활동 3차 QA에 따른 활동 그룹 관련 기능 수정 완료
kgu-clab/clab-platforms-server pull request #565
Opened 2024-09-19 15:55 UTC by SongJaeHoonn

## Summary

> #561 

활동 삭제시 활동에 참여하지 않은 admin도 삭제가 가능하도록 변경했습니다.

## Tasks

- 활동에 참여하지 않은 admin과 해당 활동의 Leader가 활동 삭제를 할 수 있도록 변경

## ETC

활동 삭제 시 사용하던 `validateLeaderPermission()`메서드에서 `GroupLeader`를 조회할 때 활동에 참여하지 않은 `admin`일 경우 `NotFoundException`을 던졌었는데, `validateLeaderPermission()`을 변경하게 되면서 연관되어 있던 다른 메서드의 권한 검사도 변경되게 되었습니다.
변경된 기능은 다음과 같습니다.
- 활동 수정, 활동 삭제, 프로젝트 진행 수정, 일정 등록, 활동 멤버 지원서 조회, 멤버 상태 변경, 멤버 직책 변경 
위의 기능들은 전부 admin도 가능해야 할 일이라고 생각되어 변경된 상태로 놔뒀는데, 잘 살펴봐주시면 감사하겠습니다.

## Screenshot

2024-09-20 00:22 UTC, mingmingmon requested changes

2024-09-20 00:22 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
> +                .orElse(member.isAdminRole());
```
return activityGroupMemberService.getGroupMemberByActivityGroupAndMember(activityGroup, member.getId())
                .map(GroupMember::isLeader)
                .orElseGet(member::isAdminRole);
```

위의 코드 처럼 `orElseGet`을 사용하시는 건 어떨까요? **인자로 넘기는 게 메소드인 경우**에 `orElse`는 항상 `member.isAdminRole()`을 실행하는 반면, `orElseGet`은 `Optional`이 비어있을 때만 해당 메서드를 실행한다는 차이점이 있어요. `member.isAdminRole()`가 계산 비용이 엄청나게 크진 않지만, 굳이 계산할 필요가 없을 경우는 불필요한 연산을 줄이기 위해 `orElseGet`을 사용하는 것이 좋을 것 같아요.

- `orElse`의 **즉시평가**
메소드에 전달된 인자가 호출 시점에서 무조건 실행이 되는 것
```
public T orElse(T other) {
    return value != null ? value : other;
}

```


- `orElseGet`의 **지연평가**
Supplier 인터페이스를 사용해 supplier.get이 필요할 때만 호출 되는 것
```
public T orElseGet(Supplier<? extends T> supplier) {
    return value != null ? value : supplier.get();
}
```


아래는 참고 자료 입니다!
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Optional.html#orElse(T)
https://giron.tistory.com/153

2024-09-20 00:24 UTC, mingmingmon commented
>활동 수정, 활동 삭제, 프로젝트 진행 수정, 일정 등록, 활동 멤버 지원서 조회, 멤버 상태 변경, 멤버 직책 변경
위의 기능들은 전부 admin도 가능해야 할 일이라고 생각되어 변경된 상태로 놔뒀는데, 잘 살펴봐주시면 감사하겠습니다.

해당 부분은 프론트분과 운영진분들 모두와 상의한 뒤에 진행하시는 것 어떨까요? 활동 리더와 ADMIN의 권한을 명확히 분리해야 할 것 같습니다. 특히 활동 수정, 프로젝트 진행 수정, 일정 등록, 멤버 상태변경, 멤버 직책 변경은 리더의 권한이라고 생각해요.

2024-09-20 02:42 UTC, Jeong-Ag commented
> > 활동 수정, 활동 삭제, 프로젝트 진행 수정, 일정 등록, 활동 멤버 지원서 조회, 멤버 상태 변경, 멤버 직책 변경
> > 위의 기능들은 전부 admin도 가능해야 할 일이라고 생각되어 변경된 상태로 놔뒀는데, 잘 살펴봐주시면 감사하겠습니다.
> 
> 해당 부분은 프론트분과 운영진분들 모두와 상의한 뒤에 진행하시는 것 어떨까요? 활동 리더와 ADMIN의 권한을 명확히 분리해야 할 것 같습니다. 특히 활동 수정, 프로젝트 진행 수정, 일정 등록, 멤버 상태변경, 멤버 직책 변경은 리더의 권한이라고 생각해요. @SWARVY @Jeong-Ag @Lets-Gitit @limehee

활동 관리에 활동 삭제, 활동 상태 변경 api가 사용되는데 이 두 가지는 `admin` 권한, 나머지는 `leader` 한정으로 권한을 정하는 것이 좋을 것 같다고 생각되는데 운영진 의견을 들어봐야 할 것 같아요. `admin`이 활동 그룹의 세부사항까지 컨트롤 하는 것은 권한 제한이 명확하지 않다고 생각해요.

2024-09-20 04:16 UTC, SWARVY commented
> > > 활동 수정, 활동 삭제, 프로젝트 진행 수정, 일정 등록, 활동 멤버 지원서 조회, 멤버 상태 변경, 멤버 직책 변경
> > > 위의 기능들은 전부 admin도 가능해야 할 일이라고 생각되어 변경된 상태로 놔뒀는데, 잘 살펴봐주시면 감사하겠습니다.
> > 
> > 
> > 해당 부분은 프론트분과 운영진분들 모두와 상의한 뒤에 진행하시는 것 어떨까요? 활동 리더와 ADMIN의 권한을 명확히 분리해야 할 것 같습니다. 특히 활동 수정, 프로젝트 진행 수정, 일정 등록, 멤버 상태변경, 멤버 직책 변경은 리더의 권한이라고 생각해요. @SWARVY @Jeong-Ag @Lets-Gitit @limehee
> 
> 활동 관리에 활동 삭제, 활동 상태 변경 api가 사용되는데 이 두 가지는 `admin` 권한, 나머지는 `leader` 한정으로 권한을 정하는 것이 좋을 것 같다고 생각되는데 운영진 의견을 들어봐야 할 것 같아요. `admin`이 활동 그룹의 세부사항까지 컨트롤 하는 것은 권한 제한이 명확하지 않다고 생각해요.

일반적인 동아리 활동에서 `admin`이 그룹의 세부사항까지 컨트롤할 일은 없으나, 리더 부재 혹은 특수한 상황에서는 `admin`이 해당 사항을 집행할 수도 있어야 하지 않을까요? 

또 `leader`와 `admin`의 성격은 조금 다르다고 생각합니다. `leader`의 경우 활동 운영이라는 특수한 목적에 의해서 부여되는 롤이지만 `admin`은 사이트 운영에 대한 전반적인 권한을 모두 관리하는 롤이고, 그에 따라 그 리더가 가지는 권한까지 관리할 수 있어야한다고 생각하기 때문입니다. 또, 계층으로 나타내봤을 떄도 `admin`은 가장 상위 단계에 존재하구요

2024-09-20 04:47 UTC, SongJaeHoonn commented
> > 활동 수정, 활동 삭제, 프로젝트 진행 수정, 일정 등록, 활동 멤버 지원서 조회, 멤버 상태 변경, 멤버 직책 변경
> > 위의 기능들은 전부 admin도 가능해야 할 일이라고 생각되어 변경된 상태로 놔뒀는데, 잘 살펴봐주시면 감사하겠습니다.
> 
> 해당 부분은 프론트분과 운영진분들 모두와 상의한 뒤에 진행하시는 것 어떨까요? 활동 리더와 ADMIN의 권한을 명확히 분리해야 할 것 같습니다. 특히 활동 수정, 프로젝트 진행 수정, 일정 등록, 멤버 상태변경, 멤버 직책 변경은 리더의 권한이라고 생각해요.

이에 대한 제 입장은 Leader가 할 수 있는 일이라면 Admin도 할 수 있는 일이여야 한다고 생각합니다. 
만약 Leader가 관리하지 못하게 되는 상황이 발생할 시 동아리를 관리하는 admin 권한을 가지고 있는 관리자가 해당 상황을 해결해 줘야 하는데, 만약 Admin이 할 수 있는 것과 Leader가 할 수 있는 것이 따로 정해지게 된다면, Admin이 할 수 없는 행위에 대해서는 Super권한이 있는 개발팀에 책임이 넘어가므로, 권한에 대한 책임이 불명확해 진다는 생각이에요.

2024-09-20 04:54 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
> +                .orElse(member.isAdminRole());
좋은 의견 감사합니다!
`orElse`와 `orElseGet`을 즉시평가와 지연평가로 구분해주셔서 더 이해하기 편하네요
`member`의 권한이 `Admin`임을 판단하는 로직은 `Optional`이 비어있을 때에만 실행하는 편이 더욱 효율적이겠네요. 반영하도록 하겠습니다!

2024-09-20 09:45 UTC, mingmingmon commented
@SongJaeHoonn 
해당 작업을 우선 머지하고, 추후에 정책을 정해서 진행하는 방식으로 정해진건가요?

2024-09-20 10:54 UTC, SongJaeHoonn commented
@mingmingmon 그렇습니다!

2024-09-20 11:29 UTC, mingmingmon approved these changes
피드백 수용 감사합니다!

2024-09-20 13:21 UTC, gwansikk commented
> 일반적인 동아리 활동에서 `admin`이 그룹의 세부사항까지 컨트롤할 일은 없으나,`leader` 부재 혹은 특수한 상황에서는 `admin`이 해당 사항을 집행할 수도 있어야 하지 않을까요?

해당 의견에 동의합니다. 정책 상 Admin의 권한은 상위 관리자로 생각하고 운영할 수 있도록 해야한다고 생각해요.

2024-09-20 13:57 UTC, limehee commented
> > > > 활동 수정, 활동 삭제, 프로젝트 진행 수정, 일정 등록, 활동 멤버 지원서 조회, 멤버 상태 변경, 멤버 직책 변경
> > > > 위의 기능들은 전부 admin도 가능해야 할 일이라고 생각되어 변경된 상태로 놔뒀는데, 잘 살펴봐주시면 감사하겠습니다.
> > > 
> > > 
> > > 해당 부분은 프론트분과 운영진분들 모두와 상의한 뒤에 진행하시는 것 어떨까요? 활동 리더와 ADMIN의 권한을 명확히 분리해야 할 것 같습니다. 특히 활동 수정, 프로젝트 진행 수정, 일정 등록, 멤버 상태변경, 멤버 직책 변경은 리더의 권한이라고 생각해요. @SWARVY @Jeong-Ag @Lets-Gitit @limehee
> > 
> > 
> > 활동 관리에 활동 삭제, 활동 상태 변경 api가 사용되는데 이 두 가지는 `admin` 권한, 나머지는 `leader` 한정으로 권한을 정하는 것이 좋을 것 같다고 생각되는데 운영진 의견을 들어봐야 할 것 같아요. `admin`이 활동 그룹의 세부사항까지 컨트롤 하는 것은 권한 제한이 명확하지 않다고 생각해요.
> 
> 일반적인 동아리 활동에서 `admin`이 그룹의 세부사항까지 컨트롤할 일은 없으나,`leader` 부재 혹은 특수한 상황에서는 `admin`이 해당 사항을 집행할 수도 있어야 하지 않을까요?
> 
> 또 `leader`와 `admin`의 성격은 다르다고 생각합니다. `leader`의 경우 활동 운영이라는 특수한 목적에 의해서 부여되는 롤이지만 `admin`은 사이트 운영에 대한 전반적인 권한을 모두 관리하는 보다 근본적인 롤이고, 그에 따라 그 `leader`가 가지는 권한까지 모두 관리할 수 있어야한다고 생각하기 때문입니다. 계층으로 나타내봤을 떄도 `admin`은 가장 상위 단계에 존재하구요
> 
> 모든 권한을 주는 것을 특정한 이유로 피해야 한다면, `admin`이 최소한 `leader`를 교체할 수 있는 등의 권한정도는 있어야 한다고 생각합니다. 그렇지만 근본적으로 하위에 존재하는 모든 권한을 관리할 수 없으면 그건 더이상 `admin`이 아니지 않을까요?
> 
> @SongJaeHoonn @mingmingmon @Jeong-Ag @gwansikk @limehee

저도 현호님의 의견에 동의합니다. `ADMIN` 역할은 말 그대로 `관리자`로서, 모든 도메인에 대한 접근 및 관리 권한을 가지고 있어야 한다고 생각합니다. 활동 도메인 내에서 `리더`라는 특정 역할이 존재한다 해도, `ADMIN` 권한은 별개로 활동 그룹에 자유롭게 접근하고 관리할 수 있어야 합니다. 특히, `관리자`가 모든 권한을 가지고 있지 않으면, 예상치 못한 상황이나 `리더`의 부재 시 문제가 발생할 수 있으며, 이로 인해 운영 효율성이 떨어질 수 있습니다. 따라서 `ADMIN`은 궁극적으로 모든 하위 권한을 포함해 시스템을 전반적으로 관리할 수 있어야 한다고 봅니다.

2024-09-20 14:03 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
>      public boolean isMemberGroupLeaderRole(ActivityGroup activityGroup, Member member) {
`.orElseGet(member::isAdminRole)` 가 추가되면서 `isMemberGroupLeaderRole()` 메소드가 리더 권한만을 검사하지 않도록 변경된 만큼, 메소드명이 이를 정확히 반영할 필요가 있다고 보여요. 현재 메소드명은 리더 권한만을 검사하는 것으로 보이므로, 이를 더 명확하게 표현하는 이름으로 수정하는 것이 좋을 것 같아요.

`hasLeaderOrAdminRole()`은 어떨까요?

2024-09-21 03:13 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
>      public boolean isMemberGroupLeaderRole(ActivityGroup activityGroup, Member member) {
좋은 피드백 감사합니다. 해당 작업을 하며 메서드명을 변경해야겠다고 생각했었는데, 수정을 안했었네요! 변경 후 말씀드리겠습니다

2024-09-21 03:21 UTC, limehee approved these changes

2024-09-21 03:23 UTC, merged