refactor: 활동 멤버 및 지원서 조회 정렬 로직 변경 완료
kgu-clab/clab-platforms-server pull request #578
Opened 2024-09-29 08:50 UTC by SongJaeHoonn

## Summary

> #577 

`활동 멤버 및 지원서 조회` api에서, 페이지에서만 정렬되도록 하는 것이 아닌, 전체 데이터를 대상으로 정렬을 한 후 페이지가 나눠지도록 변경했습니다.
또한, 정렬 시 리더가 최상단에 위치할 수 있도록 `PagedResponseDto`에 새로운 생성자를 만들고, 그에 따른 변경점을 수정했습니다.

해당 변경들은 프론트엔드 및 운영진분과 함께 의논하여 문제를 발견하고, 수정했습니다.

## Tasks

- 전체 데이터를 대상으로 정렬하도록 변경
- 리더가 최상단에 위치할 수 있도록 변경

## Results

```
{
  "success": true,
  "data": {
    "currentPage": 0,
    "hasPrevious": false,
    "hasNext": false,
    "totalPages": 1,
    "totalItems": 4,
    "take": 4,
    "items": [
      {
        "memberId": "leader",
        "memberName": "리더",
        "role": "LEADER",
        "status": "ACCEPTED",
        "applyReason": ""
      },
      {
        "memberId": "202500001",
        "memberName": "설윤",
        "role": "NONE",
        "status": "WAITING",
        "applyReason": "백엔드에 관심이 있어서"
      },
      {
        "memberId": "202500003",
        "memberName": "김민지",
        "role": "MEMBER",
        "status": "ACCEPTED",
        "applyReason": "백엔드에 관심이 있어서"
      },
      {
        "memberId": "202500002",
        "memberName": "오해원",
        "role": "NONE",
        "status": "REJECTED",
        "applyReason": "백엔드에 관심이 있어서"
      }
    ]
  }
}
```

2024-09-29 09:09 UTC, limehee requested changes

2024-09-29 09:09 UTC, limehee commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable, boolean leaderUp) {
`PagedResponseDto`는 프로젝트 전반에서 사용하는 전역적인 응답 전용 DTO에요. 특정 도메인에서만 필요한 생성자를 이 DTO에 추가하는 것은 책임의 분리 원칙에 어긋나요. 도메인의 비즈니스 로직은 해당 도메인 내에서 처리하고, `PagedResponseDto`는 응답 데이터를 전송하는 역할만 하도록 설계하는 것이 적절해요.

2024-09-29 16:15 UTC, limehee requested changes

2024-09-29 16:15 UTC, limehee commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
추가한 `public PagedResponseDto(List<T> ts, Pageable pageable)` 생성자에서 `List`를 매개변수로 받는 점은 기존 생성자들과 일치하지만, 내부 처리 로직에서 차이가 있어 향후 예상치 못한 응답 결과와 코드 변경의 어려움을 초래할 가능성이 있어요.

구체적으로, 추가하신 생성자는 `applySortingAndSlicing` 메서드를 사용하여 정렬 및 슬라이싱을 처리하는 반면,  기존 생성자들은 슬라이싱을 별도로 처리하지 않고 있어요. 이는 일관성이 부족한 설계라고 생각되고, 두 가지 처리 방식이 상이한 결과를 낼 수 있어 유지보수나 코드 가독성에 문제가 될 수 있어요.

모든 `List` 기반 생성자에서 동일하게 슬라이싱과 정렬을 처리하거나, 해당 이슈에서 추가된 슬라이싱 로직을 다른 코드와 동일하게 응용 또는 영속 계층에서 사전 처리하여, 간결한 처리를 유지하는 방법을 제안합니다.

2024-09-29 18:15 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
저는 `PagedResponseDto`에 있는 여러 생성자들의 매개변수가 다 다르기에 다양한 도메인에서 `PagedResponseDto`를 사용할 때 내부 처리 로직을 보며 선택하고 사용할 수 있기에, 선택하고 활용할 수 있는 폭이 넓어진다고 생각했습니다.

제가 추가한 `applySortingAndSlicing` 메서드는,  추후에라도 정렬 후 슬라이싱이 필요한 경우에 `public PagedResponseDto(List<T> ts, Pageable pageable)`에서 상황에 맞게 사용이 될 수 있고,

만약 다른 `List`기반 생성자들에서 동일하게 슬라이싱과 정렬을 사용하게 되면, 이미 다른 방식으로 슬라이싱되고 정렬 처리되어 들어온 리스트가 있다면 사용할 수 있는 생성자가 없어지게 된다고 생각했습니다.(선택의 폭이 줄어듦)

하지만 말씀해주신 `일관성이 부족한 설계`라는 것은 깊이 인정합니다! 애초에 정렬이나 슬라이싱을 한 군데에서 진행하는 것이 유지보수나 새로운 기능의 추가 시에 편하니까요.

사실 슬라이싱 로직을 영속 계층에서 사전 처리하는 것이 결국 `Page` 객체를 만들어야 하는 것인데, 로직이 복잡하여 `Page`를 통해 조회할 수 없는 기능들은 사전 처리가 힘들기 때문에, 저는 모든 `List` 기반 생성자에서 동일하게 슬라이싱과 정렬을 적용하는 편이 좋아보입니다. 

기존에 `List` 기반 생성자를 사용하고 있던 코드의 사전 슬라이싱과 정렬을 제거하고 `PagedResponseDto`에서 적용하면 될 것 같아 비교적 간단하게 변경할 수 있을 것 같습니다! 어떻게 생각하시나요?

2024-09-30 01:07 UTC, mingmingmon commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
`public PagedResponseDto(List<T> ts, Pageable pageable)` 생성자를 통해` PagedResponseDto` 객체를 만든다면, `applySortingAndSlicing()`가 존재하기 때문에 무조건 슬라이싱이 필요한 경우에만 사용할 수 있는 것 같아요.

이는 @limehee님이 말씀해주신 `List<>`를 매개변수로 받고 있는 다른 생성자들과는 다른 로직이 담겨있습니다. 이 부분을 @SongJaeHoonn님께서는 슬라이싱이 필요한 상황에서 사용할 수 있는 로직이니 확인하고 사용하자라고 말씀해주셨어요.

저는 이번 수정사항이 "필요한 상황에서 사용할 수 있기에 로직을 확인하고 알맞은 생성자를 사용하자"는 해석보다는 "PagedResponseDto 객체를 만들 때 **로직을 확인하고** 상황에 맞게 사용하자"라는 뜻으로, 사용하는데 불편함이 더 커진 것 같아요. @SongJaeHoonn님 말씀처럼 로직을 확인하고 생성자를 선택해야 하니까요.

해당 부분이 일반적인 메소드라면 메소드명으로 이러한 로직의 의미를 표현할 수 있지만, 이번 작업의 대상은 생성자잖아요? 그러다보니, **전달되는 매개변수의 차이점으로 필요한 상황에 알맞음을 판단**해야 됩니다.

따라서 내부 로직을 직접 확인하는 비용보다는 @limehee님이 말씀해주신 `List<>`를 매개변수로 삼는 다른 생성자들과 일관성을 지킬 수 있도록 수정하는 게 좋을 것 같아요.

2024-09-30 05:47 UTC, limehee commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
> 기존에 List 기반 생성자를 사용하고 있던 코드의 사전 슬라이싱과 정렬을 제거하고 PagedResponseDto에서 적용하면 될 것 같아 비교적 간단하게 변경할 수 있을 것 같습니다! 어떻게 생각하시나요?

영속 계층에서 전체 데이터를 조회한 후 응답 계층에서 슬라이싱하는 방식은 데이터 처리 속도 저하와 메모리 사용량 증가, I/O 증가 등과 같은 부작용을 가져올 수 있어요. 이번 작업처럼 부득이하게 조회 후 슬라이싱이 필요하다면 어쩔 수 없지만, 다른 경우에는 가능한 한 영속 계층에서 페이지네이션을 적용하여 필요한 데이터만 조회하는 것이 성능 최적화와 리소스 관리 측면에서 더 적절하다고 생각해요.

2024-09-30 05:50 UTC, limehee commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
이번 작업은 특정한 케이스에 한정되므로, 기존 로직을 유지한 채 DTO 변환을 완료한 후 응용 계층에서 반환 시 슬라이싱을 적용하는 방법도 괜찮을 것 같아요.

2024-09-30 06:12 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
@mingmingmon 
저는 관점을 약간 다르게 봤었는데, `무조건 슬라이싱이 필요한 경우에만 사용`이 아닌 `슬라이싱이 필요한 경우에도 사용 가능`의 관점에서 봤었습니다. 

그리고 이미 존재하는 무언가를 사용할 때에는 내부에서 돌아가는 로직을 확인하고 사용하는 것은 당연하다고 생각했었고, 각 생성자의 매개변수가 다르다면 그에 맞는 용도가 따로 있는 것이므로 내부 로직은 다를 수 밖에 없기도 합니다. 내부 로직이 다르다면 각 생성자가 고유의 책임을 가지게 되는 것이므로 객체 지향 설계에 부합한다고 생각했습니다! 또한 이미 로직에 `JavaDocs`가 포함되어 있기 때문에 쉽게 구별이 가능하다고 생각했습니다. 이게  `JavaDocs`가 존재하는 이유이기도 하니까요!

하지만 말씀해주신대로 이미 `List`를 매개변수로 받는 생성자들의 일관성이 다르다는것에 대해 동감합니다. 따라서 저도 변경하면 좋을 것 같긴 하지만 현재 `ActivityGroup` 도메인 내에서 리더를 최상단에 배치하고 나머지를 정렬하고 슬라이싱하는 방법을 떠올리기가 쉽지 않더라고요. 현재는 이렇게 `PagedResponseDto`에서 처리하는 편이 가장 좋다고 생각했습니다.

2024-09-30 06:19 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
> 이번 작업은 특정한 케이스에 한정되므로, 기존 로직을 유지한 채 DTO 변환을 완료한 후 응용 계층에서 반환 시 슬라이싱을 적용하는 방법도 괜찮을 것 같아요.

현재 구조에서 모든 데이터에 대해 정렬 후 슬라이싱을 적용하려면 `PagedResponseDto`에서 정렬을 적용하는 로직도 응용 계층에서 처리하도록 하는게 좋을 것 같습니다!

2024-09-30 06:48 UTC, limehee commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
`PagedResponseDto` 변환 과정에서 페이지네이션 객체의 `Sort` 관련 정보를 확인하고 데이터를 정렬시키는게 포함되는데, 이거랑 무관하게 재정렬이 필요하다는 말씀이실까요?

2024-09-30 12:42 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
만약 슬라이싱을 응용 계층에서 처리하게 된다면 정렬도 응용 계층에서 처리하는 편이 낫지 않나요?
이렇게 되면 `PagedResponseDto`는 정말 응답을 생성해주는 역할만 하게 됩니다.

2024-09-30 13:09 UTC, limehee commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
정렬도 응용 계층에서 처리하게 된다면, `PagedResponseDto`는 응답을 포맷팅하고 생성하는 본래의 역할만 하게 되어 책임의 분리가 명확해진다는 부분에 동의합니다.

다만, 기존에 `PagedResponseDto`에서 정렬을 수행하던 API들이 이미 존재하고 있기 때문에, 이를 모두 일일이 수정하고 테스트하는 것은 현실적으로 어렵다고 생각돼요. 따라서 이번 작업에서 추가된 슬라이싱은 응용 계층에서 처리하도록 하고, 기존에 `List`를 매개변수로 받아 생성하는 생성자를 `Deprecated`로 처리한 뒤, `Sorting` 로직을 별도의 `Util` 클래스로 분리하여 공통적으로 사용할 수 있도록 하는 방법은 어떨까 싶습니다. 이렇게 하면 새로운 API나 수정된 API에서 `List`를 다룰 때 응용 계층에서 정렬과 슬라이싱을 처리하도록 유도할 수 있고, 기존 API들은 점진적으로 리팩토링할 수 있을 것으로 보여요.

정리하자면, 영속 계층에서 슬라이싱과 정렬을 처리할 수 없는 상황이라면 응용 계층에서 이를 수행하는 것이 책임의 분리를 명확하게 하고, 이를 단계적으로 적용하는 방식이 적절하다고 생각합니다.

2024-09-30 13:12 UTC, limehee commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
제가 제안한 방법대로 진행한다면, 기존의 `PageableUtils`를 활용하거나, 새로운 `Util` 클래스를 작성하여 `List`를 슬라이싱하고 정렬하는 메서드를 추가하는 방식으로 해결할 수 있을 것 같아요.

2024-10-01 09:05 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
일단 이번 작업에서는 응용 계층에서 새로운`Util` 클래스를 통해 정렬과 슬라이싱을 하고, `PagedResponseDto`에 `PagedResponseDto`에서 별도의 정렬을 진행하지 않는 새로운 `List` 기반 생성자를 만들어 처리하고, 기존에 있던 두 개의 `List` 기반 생성자는 `Deprecated`로 처리하자는 말씀으로 이해했습니다. 제가 이해한 바가 맞을까요? 
맞다면 작업 시작하겠습니다!

2024-10-01 09:23 UTC, limehee commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
네 맞습니다 :)

2024-10-02 11:33 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
@mingmingmon @limehee 
기존 `PagedResponseDto`에 있는 정렬과 슬라이싱 로직을 `Deprecated`처리 후 `PaginationUtils`로 옮겼습니다! 확인 부탁드립니다.

2024-10-02 11:44 UTC, limehee commented on src/main/java/page/clab/api/global/util/PaginationUtils.java
> +        Comparator<T> comparator = sort.stream()
```java
private List<T> applySortingIfNecessary(List<T> items, Sort sort) {
    if (sort.isSorted()) {
        return sortItems(items, sort);
    }
    return items;
}
```

기존 로직처럼 `isSorted()`를 통해 Sort 정보를 확인하고 정렬이 필요한 경우에만 정렬 로직이 작동하게 하는건 어떨까요? 지금의 방식은 Sort 객체가 비어있을 경우에도 정렬을 시도해서 불필요한 연산이 발생할 수 있을 것 같아요.

### 코드 제안
```java
public <T> List<T> applySorting(List<T> items, Sort sort) {
    if (!sort.isSorted()) {
        return items;  // 정렬이 필요하지 않은 경우 원본을 그대로 반환
    }

    Comparator<T> comparator = sort.stream()
            .map(order -> {
                Comparator<T> itemComparator = Comparator.comparing(
                        item -> {
                            try {
                                return (Comparable) extractFieldValue(item, order.getProperty());
                            } catch (InvalidColumnException e) {
                                throw new RuntimeException(e);
                            }
                        }
                );
                return order.isAscending() ? itemComparator : itemComparator.reversed();
            })
            .reduce(Comparator::thenComparing)
            .orElseThrow(IllegalArgumentException::new);

    return items.stream()
            .sorted(comparator)
            .toList();
}
```

2024-10-02 11:45 UTC, limehee commented on src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
> +    public PagedResponseDto(List<T> ts, Pageable pageable) {
제안 반영해주셔서 감사합니다 :)

2024-10-02 11:49 UTC, limehee commented
`PaginationUtils` 내에 정의된 메소드들을 `static`으로 전환하는 것을 제안드립니다.
Util 클래스는 일반적으로 객체 상태와 무관하게 반복적으로 사용되는 공통 기능을 제공하기 때문에, 메소드를 `static`으로 선언하여 인스턴스 생성 없이 호출할 수 있도록 하는 것이 좋다고 생각해요. 특히, 정렬이나 슬라이싱과 같은 기능은 상태를 가지지 않으므로 `static`으로 처리하는 것이 적절하다고 생각해요.

2024-10-02 11:55 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/util/PaginationUtils.java
> +        Comparator<T> comparator = sort.stream()
정렬이 필요하지 않은 경우를 생각하지 못했네요! 변경 완료했습니다 감사합니다!

2024-10-02 12:04 UTC, limehee approved these changes

2024-10-02 12:04 UTC, SongJaeHoonn commented
> `PaginationUtils` 내에 정의된 메소드들을 `static`으로 전환하는 것을 제안드립니다.

좋은 말씀 감사합니다..!
`유틸리티` 클래스이므로, 어디서든 사용될 수 있는 공통 기능이기에 객체 생성 없이 간편하게 메서드를 사용할 수 있어 코드의 효율성과 간결성을 높일 수 있겠네요.
많이 배워갑니다!!

2024-10-03 12:10 UTC, mingmingmon approved these changes

2024-10-03 12:19 UTC, merged