feat: 핫 게시글 조회 api 구현 완료
kgu-clab/clab-platforms-server pull request #610
Opened 2024-11-08 17:34 UTC by SongJaeHoonn

## Summary

> #607 

게시판 상단에 핫 게시글을 노출하는 기능을 위해, 지난주의 인기 게시글을 조회하는 api를 구현했습니다.

## Tasks

- hot 게시글 조회 로직 구현

## ETC

- 추후 핫 게시글 개수의 유연한 변경을 위해 파라미터에 `size`를 추가해 개수 조절이 가능하도록 구현했습니다. (기본값은 5)
- 지난 주의 핫 게시글이 `size`개보다 적다면, 이번 주를 기준으로 두 주 전, 세 주 전... 을 계속 조회하여 핫 게시글이 `size` 개수가 될 때까지 반복합니다.
- 만약 전체 게시글의 개수가 `size`개보다 적다면 전체 게시글을 반응 순으로 정렬 후 반환합니다.

## API Response

- `2024-11-08`일에 api 호출했을 때 (size = 3)

1번 게시글 댓글 1, 이모지 2
2번 게시글 댓글 1, 이모지 5
3번 게시글 댓글 1, 이모지 1
```
{
  "success": true,
  "data": [
    {
      "id": 2,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "free",
      "title": "Free Board Title 1",
      "content": "This is a free board content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-10-30T17:30:00"
    },
    {
      "id": 1,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "notice",
      "title": "Notice Title 1",
      "content": "This is a notice content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-10-29T21:00:00"
    },
    {
      "id": 3,
      "writerId": null,
      "writerName": "User2",
      "category": "qna",
      "title": "QnA Title 1",
      "content": "This is a QnA content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-11-02T23:45:00"
    }
  ]
}
```

1번 게시글 댓글 1, 이모지 1
2번 게시글 댓글 1, 이모지 1
3번 게시글 댓글 1, 이모지 1
-> 최신 순 정렬
```
{
  "success": true,
  "data": [
    {
      "id": 3,
      "writerId": null,
      "writerName": "User2",
      "category": "qna",
      "title": "QnA Title 1",
      "content": "This is a QnA content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-11-02T23:45:00"
    },
    {
      "id": 2,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "free",
      "title": "Free Board Title 1",
      "content": "This is a free board content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-10-30T17:30:00"
    },
    {
      "id": 1,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "notice",
      "title": "Notice Title 1",
      "content": "This is a notice content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-10-29T21:00:00"
    }
  ]
}
```

- 만약 지난 주의 게시글이 `size - 1`개 이하일 때

11월 8일 기준 지난주는 10월 28일 ~ 11월 3일 (1, 2번)
1번 → 댓글 1개, 이모지 0개
2번 → 댓글 0개, 이모지 0개
5번, 6번, 7번 → 지지난주 핫게시글
```
{
  "success": true,
  "data": [
    {
      "id": 1,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "notice",
      "title": "Notice Title 1",
      "content": "This is a notice content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-10-29T21:00:00"
    },
    {
      "id": 2,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "free",
      "title": "Free Board Title 1",
      "content": "This is a free board content.",
      "commentCount": 0,
      "imageUrl": null,
      "createdAt": "2024-10-30T17:30:00"
    },
    {
      "id": 7,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "notice",
      "title": "Notice Title 7",
      "content": "This is a notice content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-10-24T21:00:00"
    }
  ]
}
```

2024-11-09 10:17 UTC, mingmingmon requested changes

2024-11-09 10:17 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +
이 부분에서 게시글의 총 개수가 size보다 작다는 판단을 hotBoards를 탐색하기 전에 하는 게 더 효율적일 것 같아요.

게시글의 총 개수가 size보다 적다면 47~49번째 로직으로 `getHotBoards` 메소드가 종료될 수 있는데, 현재는 불필요하게 `getHotBoardsForWeek`메소드를 무조건 실행하게 됩니다.

2024-11-09 10:17 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +
54번째 while문으로 필요한 핫 게시글 개수만큼 이전 주차에 작성된 게시글을 탐색하는 로직이 좋은 것 같습니다.

다만, 해당 로직으로 44번째 작성하신 바로 전 주의 핫 게시글 판단 로직까지 포함해서 일반화할 수 있을 것 같습니다. 
즉, 44번째 줄을 51번째로 내리고, weeksAgo를 1부터 시작하여 hot 게시글의 개수 채우기 로직을 일반화시켜주세요!

2024-11-09 10:24 UTC, mingmingmon reviewed
메소드추출을 잘 해주셔서 로직을 이해하기 편했습니다.

다만, 저와 @SongJaeHoonn님, @Jeong-Ag님이 핫 게시글 정책에 대해 회의를 했을 때,
일주일마다 핫 게시글을 새로 등재하기로 이야기 나눴던 것 같아요. 

지금까지의 작업으로는 매번 API를 호출할 때마다 핫 게시글을 판단하는 쿼리문이 실행되는 것 같습니다. 즉, 일주일에 한 번 핫 게시글이 갱신 되는 것이 아니라 페이지 방문할 때마다 핫 게시글이 계속 갱신 되는 것 같아요. (물론, 게시글이 많이 올라오고, 반응도 그만큼 많이 달려야겠지만요)

이러한 동작은 저희가 처음 설계한 정책과는 조금 다른 모습이기도 하고, api 호출 시 발생하는 쿼리가 많아서 부담이 되어보입니다. 

따라서 핫 게시글 선정 로직을 매주 스케쥴링을 걸어 DB에 저장해두는 방식을 제안드립니다

2024-11-11 19:44 UTC, SongJaeHoonn commented
> 지금까지의 작업으로는 매번 API를 호출할 때마다 핫 게시글을 판단하는 쿼리문이 실행되는 것 같습니다. 즉, 일주일에 한 번 핫 게시글이 갱신 되는 것이 아니라 페이지 방문할 때마다 핫 게시글이 계속 갱신 되는 것 같아요. (물론, 게시글이 많이 올라오고, 반응도 그만큼 많이 달려야겠지만요)

@mingmingmon 
현재 로직에서도 일주일에 한 번 핫 게시글이 갱신되고 있어요. 
API를 호출할 때마다, 현재 시각을 기준으로 지난 주에 가장 반응이 많았던 핫 게시글을 조회해 가져오는 방식입니다..!

그러나 현재 방식은 API를 호출할 때마다 댓글 수와 이모지 수를 계산하는 복잡한 로직들과 복잡한 조회 방식이 요구되므로 원래의 DB에 `isHotBoard` 같은 새로운 칼럼을 넣어 일주일마다 스케줄링 되는 방식이 현재 구조에서는 더욱 효율적일 것 같네요!  
소중한 의견 감사합니다 🙇‍♂️

2024-11-11 19:46 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +
이 부분을 놓쳤네요! 의견 감사합니다

2024-11-11 20:06 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +
제가 이렇게 따로 구현한 의도는, 
`getHotBoardsForWeek()`메서드에서는 바로 지난 주의 핫 게시글 (여기서는 반응 순으로 정렬됨)
반면 while문에서는 반복해서 이전 주로 이동해서 Hot 게시글을 보충하게 되는데, (여기서는 지지난 주부터의 핫 게시글 중에서 반응 수와는 상관 없이 가장 최신 게시글을 가져오도록 정렬)

이 두 개의 차이가 정렬 방식이라 두 개를 분리할 수밖에 없었습니다. 
말씀해주신게 다른 의도가 있으신건가요?

2024-11-12 10:27 UTC, limehee requested changes

2024-11-12 10:27 UTC, limehee commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +        LocalDateTime startOfWeek = LocalDate.now().minusWeeks(weeksAgo).with(java.time.DayOfWeek.MONDAY).atStartOfDay();
`DayOfWeek`를 import하지 않고 `java.time` 패키지명을 명시적으로 작성한 이유가 있을까요?

2024-11-12 10:27 UTC, limehee commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +    private List<Board> sortAndLimit(int size, List<Board> boardsForWeek) {
`sortAndLimit()` 메서드명은 객체 유형과 정렬 기준을 명확히 전달하지 않아 가독성이 떨어질 수 있어요. 정렬 기준인 `reaction 수`와 `생성 날짜`를 메서드명에 포함하여, 메서드가 반환하는 객체의 성격을 더 명확히 드러내는게 좋아 보여요. `sortBoardsByReactionAndDateWithLimit()`과 같이 의미를 명확히 드러내는 메소드명을 제안합니다.

2024-11-12 10:27 UTC, limehee commented on src/main/java/page/clab/api/domain/community/board/adapter/in/web/HotBoardsRetrievalController.java
> +    @Operation(summary = "[G] 커뮤니티 핫 게시글 목록 조회", description = "ROLE_GUEST 이상의 권한이 필요함<br>" +
`핫 게시글`보다는 `인기 게시글`이라고 많이 표현하다보니, `핫`이라는 단어를 봤을 때 다시 한 번 생각하게 되는 경향이 있어요. `인기`라는 표현은 어떨까요?

2024-11-12 10:42 UTC, limehee commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +    private int getTotalReactionCount(Board board) {
인기 게시글을 선정하는 기준은 상황에 따라 정하기 나름이기에 변동 가능성이 크다고 판단돼요. `Strategy` 패턴을 이용하여 언제든 선정 기준을 변경 가능하도록 설계하는 방향을 제안드려요.

2024-11-12 10:59 UTC, limehee commented
> 그러나 현재 방식은 API를 호출할 때마다 댓글 수와 이모지 수를 계산하는 복잡한 로직들과 복잡한 조회 방식이 요구되므로 원래의 DB에 `isHotBoard` 같은 새로운 칼럼을 넣어 일주일마다 스케줄링 되는 방식이 현재 구조에서는 더욱 효율적일 것 같네요! 소중한 의견 감사합니다 🙇‍♂️

@SongJaeHoonn 님의 제안도 효율적인 접근 방식이지만, 추가적으로 캐싱 전략을 활용하는 방안도 고려해보시면 좋을 것 같아요. 새로운 컬럼을 추가할 경우 테이블 관리와 데이터 정합성 유지가 더 복잡해질 수 있고, 매번 연산이 발생할 때마다 기존 데이터를 동기화해야 한다는 부담이 있어요.

이번 인기 게시글 기능처럼 정합성이 절대적으로 요구되지 않고 주기적으로 갱신되는 데이터라면, TTL(Time to Live) 설정이 가능한 Redis와 같은 캐시 시스템을 통해 성능을 최적화할 수 있어요. 예를 들어, 인기 게시글 정보를 Redis에 저장하고 일정 시간마다 갱신하도록 설정하면 데이터베이스 부하를 줄이면서도 빠른 응답성을 유지할 수 있어요.

또한, 현재는 카테고리와 무관하게 인기 게시글이 관리되는 것으로 보이는데, 카테고리별 인기 게시글을 도입하면 사용자에게 더욱 맞춤화된 정보를 제공할 수 있을 것으로 보여요.

2024-11-12 11:03 UTC, limehee commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +        return commentCount.intValue() + emojiCount;
댓글 개수와 이모지 개수를 합산하여 인기도를 산출하는 것도 좋은 방법이지만, 댓글 길이와 같은 추가적인 정보도 통계 척도로 활용하고 가중치를 부여하는 방식도 고려해보면 좋을 것 같아요. 이 부분은 단순한 제안이니 참고해주시면 감사하겠습니다.

2024-11-12 11:05 UTC, limehee commented
프론트에서 인기 게시글을 어떻게 표시할지는 모르지만, 일반 게시글과 함께 하나의 목록으로 표시된다면, 게시글 조회 시 인기 게시글 정보를 함께 반환하여 API 호출 횟수를 줄이는 방법도 고려해보시면 좋을 것 같네요.

2024-11-12 23:55 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +        if (allBoards.size() < size) {
`size`값으로 음수가 넘어올 것이라는 생각은 안해봤는데, 처리가 필요하겠군요

2024-11-12 23:55 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +        LocalDateTime startOfWeek = LocalDate.now().minusWeeks(weeksAgo).with(java.time.DayOfWeek.MONDAY).atStartOfDay();
import 하는것을 깜빡했네요. 수정하겠습니다

2024-11-12 23:57 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/adapter/in/web/HotBoardsRetrievalController.java
> +    @Operation(summary = "[G] 커뮤니티 핫 게시글 목록 조회", description = "ROLE_GUEST 이상의 권한이 필요함<br>" +
사실 회의 과정에서 핫 게시글이라고 표현하다보니, 네이밍이 이대로 굳어졌는데 저도 `인기 게시글`이 확실하고 좋다고 생각합니다.
회의 후 수정하도록 하겠습니다

2024-11-13 00:14 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +    private int getTotalReactionCount(Board board) {
`Strategy`패턴이 무엇인지 몰라 어떤 것인지 찾아봤는데, 다양한 전략들을 쉽게 갈아끼울 수 있는 재밌고 효율적인 디자인 패턴인 것 같습니다.
실제로 수시로 기준이 변경될 때 더욱 효율적인 패턴이라고 생각합니다.
그러나 현재로서는 아직 선정 기준이 한 개 밖에 없는데, 전략 하나를 관리하기 위해서 기존 코드를 확장하며 `Strategy`패턴을 사용하는 것이 좋은지는 잘 모르겠어요..!
추후 인기 게시글 선정 요구사항이 추가로 생길 때 이러한 전략 패턴을 적용하는게 맞다고 생각하는데, 어떤게 정답인걸까요?

2024-11-13 00:24 UTC, SongJaeHoonn commented
> 이번 인기 게시글 기능처럼 정합성이 절대적으로 요구되지 않고 주기적으로 갱신되는 데이터라면, TTL(Time to Live) 설정이 가능한 Redis와 같은 캐시 시스템을 통해 성능을 최적화할 수 있어요. 예를 들어, 인기 게시글 정보를 Redis에 저장하고 일정 시간마다 갱신하도록 설정하면 데이터베이스 부하를 줄이면서도 빠른 응답성을 유지할 수 있어요.
> 
> 또한, 현재는 카테고리와 무관하게 인기 게시글이 관리되는 것으로 보이는데, 카테고리별 인기 게시글을 도입하면 사용자에게 더욱 맞춤화된 정보를 제공할 수 있을 것으로 보여요.

Redis를 사용하는 것이 익숙하지 않아 이런 방법은 생각해보지 않았는데, 인메모리로 동작하는 Redis 특성상 조회가 빠르고 DB에 부담을 주지 않아 좋을 것 같아요..! 고려해보도록 하겠습니다.

그리고, 카테고리별 인기 게시글을 생각해보긴 했지만 회의 결과 활발하지 않은 카테고리는 인기 게시글이 계속 고정되거나 아예 올라오지 않을 가능성도 고려하여 모든 카테고리에서 전체 게시글 중의 인기 게시글을 표시하기로 결정했습니다.

2024-11-13 00:24 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +        return commentCount.intValue() + emojiCount;
참고하겠습니다!

2024-11-13 00:48 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +    private int getTotalReactionCount(Board board) {
제 개인적인 의견은 미래의 확장성을 위해서 지금 `strategy` 패턴을 적용하는 것이 좋을 것 같습니다.

지금 당장은 댓글과 이모지의 개수의 단순 합계로 인기 게시글을 선정하고 있어서 기준이 간단합니다. 그치만 아래쪽에 다룬 내용처럼 다른 정보(댓글 길이 등등) 기준으로 인기 게시글을 선정하는 경우를 고려해볼 수 있을 것 같아요. 

그리고 저는 요즘 멤버스가 **1년 동안 있는 다양한 이벤트(한글날, 만우절, 크리스마스) 등등에 맞는 컨셉**으로 웹페이지가 꾸며지면 좋을 것 같다는 생각을 하곤 했습니다. 만약 이러한 부분까지 고려한다면 각 컨셉에 맞게 인기 게시글의 선정 기준도 달라질 수 있을 것 같아요. (예를 들어 **한글날의 인기 게시글은 외래어를 최소로 사용한 게시글이라던가** 등등)

이런 부분을 고려하면 현재 상태에서 `strategy` 패턴을 사용해주는 것이 좋아보입니다.

2024-11-13 00:57 UTC, mingmingmon commented
> 프론트에서 인기 게시글을 어떻게 표시할지는 모르지만, 일반 게시글과 함께 하나의 목록으로 표시된다면, 게시글 조회 시 인기 게시글 정보를 함께 반환하여 API 호출 횟수를 줄이는 방법도 고려해보시면 좋을 것 같네요.

저는 인기 게시글 조회 API를 따로 추출하는 것이 좋을 것 같아요. 

현재 일반 게시글 조회 시에 페이지네이션이 적용되어있너뇨. 만약 일반 게시글 조회에서 인기 게시글을 함께 반환하도록 한다면, 10개의 일반게시글 + 5개의 인기 게시글이 함께 반환되는 형태가 될 것 같습니다. 그렇게 되면 responseDto가 더욱 복잡해지고, 사용자가 페이지를 넘길 때 마다 동일한 정보인 5개의 인기 게시글이 중복해서 전달될 것 같아요.

2024-11-13 01:01 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/community/board/adapter/in/web/HotBoardsRetrievalController.java
> +    @Operation(summary = "[G] 커뮤니티 핫 게시글 목록 조회", description = "ROLE_GUEST 이상의 권한이 필요함<br>" +
`인기`라는 표현이 더 명확하고 좋은 것 같습니다!

2024-11-13 01:41 UTC, limehee commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardsRetrievalService.java
> +    private int getTotalReactionCount(Board board) {
재훈님께서 말씀하신대로 당장은 선정 기준이 하나만 세워져있어 오버엔지니어링의 가능성이 있다는 점은 동의해요. 다만, @mingmingmon 리더님이 남기신 코멘트를 보았을 때 충분히 변동 가능성이 보여요. 리더님의 계획에 따라 `Strategy` 패턴을 미리 적용하는게 향후 확장할 때 유리할 것으로 여겨지네요.

2024-11-13 02:14 UTC, limehee commented
> 저는 인기 게시글 조회 API를 따로 추출하는 것이 좋을 것 같아요.
> 
> @limehee 님이 제안 주신 방식으로 구현하게 되면 페이지네이션된 결과(10개의 일반 게시글)와 다른 응답 객체(5개의 인기 게시글)을 다시 묶어서 responseDto로 반환하는 방식일 것 같은데, 제가 이해한 바가 맞을까요?
> 
> 현재 일반 게시글 조회 시에 페이지네이션이 적용되어있어요. 만약 일반 게시글 조회에서 인기 게시글을 함께 반환하도록 한다면, 10개의 일반게시글 + 5개의 인기 게시글이 함께 반환되는 형태가 될 것 같습니다. 그렇게 되면 responseDto가 더욱 복잡해지고, 사용자가 페이지를 넘길 때 마다 동일한 정보인 5개의 인기 게시글이 중복해서 전달될 것 같아요.

제가 코드를 꼼꼼히 살펴보지 못하고 이전 코멘트에서 "일반 게시글"이라는 모호한 표현을 사용하면서 혼동을 드린 것 같아요. 이에 따라 남겨주신 의견과 다소 어긋난 부분이 있을 수 있다는 점 양해 부탁드립니다.

`retrieveHotBoards()`의 반환형을 고려할 때, 커뮤니티 탭의 `모아보기`와 유사한 형태로 인기 게시글을 보여주고자 하는 것으로 예상돼요. 인기 게시글을 모아보기처럼 사용자에게 제공할 계획이라면, 둘의 성격이 다르므로 현재 구조대로 별도의 API로 제공하는 것이 더 적절해 보이네요. 혼동을 드린 점 다시 한번 사과드립니다.

2024-11-27 00:19 UTC, SongJaeHoonn commented
@limehee @mingmingmon 
우선 질 높은 코드리뷰에 감사드리며, 제안주신 사항들 수정 및 리팩토링 완료했습니다.

## 변경 사항
1. 인기 게시글 저장에 `Redis` 사용
  - redis에서 저장 및 조회시 `RedisTemplate`을 사용했습니다. (정렬 순서 문제로 인함)
3. 일주일에 한 번만 저장되도록 스케줄링
4. size 고정 (redis 사용으로 인함)
5. `Strategy` Pattern 적용 

Strategy 패턴 적용시 전략 클래스들은 일단 `service` 패키지에 넣어뒀는데 더 좋은 방안이 있다면 리뷰 부탁드립니다!

## 테스트

id 2, 3 ⇒ 지지지난주 2번 댓글 한개
id 4, 5 → 지지난주 4번 댓글 한개
id 6, 7 → 지난주 
id 8 → 이번주 8번 댓글 한개
결과 : 7, 6, 5, 4, 2

```
{
  "success": true,
  "data": [
    {
      "id": 7,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "notice",
      "title": "Notice Title 7",
      "content": "This is a notice content.",
      "commentCount": 0,
      "imageUrl": null,
      "createdAt": "2024-11-19T21:00:00"
    },
    {
      "id": 6,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "notice",
      "title": "Notice Title 7",
      "content": "This is a notice content.",
      "commentCount": 0,
      "imageUrl": null,
      "createdAt": "2024-11-18T21:00:00"
    },
    {
      "id": 5,
      "writerId": null,
      "writerName": "User3",
      "category": "organization",
      "title": "Club News Title 1",
      "content": "This is a club news content.",
      "commentCount": 0,
      "imageUrl": null,
      "createdAt": "2024-11-12T21:00:00"
    },
    {
      "id": 4,
      "writerId": "202500003",
      "writerName": "김민지",
      "category": "graduated",
      "title": "Graduated Board Title 1",
      "content": "This is a graduated board content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-11-11T21:00:00"
    },
    {
      "id": 2,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "free",
      "title": "Free Board Title 1",
      "content": "This is a free board content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-11-04T21:00:00"
    }
  ]
}
```

스케줄링 후 (8번을 지난주로 옮김)
결과 : 8, 7, 6, 5, 4
```
{
  "success": true,
  "data": [
    {
      "id": 8,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "notice",
      "title": "Notice Title 7",
      "content": "This is a notice content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-11-20T22:00:00"
    },
    {
      "id": 7,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "notice",
      "title": "Notice Title 7",
      "content": "This is a notice content.",
      "commentCount": 0,
      "imageUrl": null,
      "createdAt": "2024-11-19T21:00:00"
    },
    {
      "id": 6,
      "writerId": "202500001",
      "writerName": "설윤",
      "category": "notice",
      "title": "Notice Title 7",
      "content": "This is a notice content.",
      "commentCount": 0,
      "imageUrl": null,
      "createdAt": "2024-11-18T21:00:00"
    },
    {
      "id": 5,
      "writerId": null,
      "writerName": "User3",
      "category": "organization",
      "title": "Club News Title 1",
      "content": "This is a club news content.",
      "commentCount": 0,
      "imageUrl": null,
      "createdAt": "2024-11-12T21:00:00"
    },
    {
      "id": 4,
      "writerId": "202500003",
      "writerName": "김민지",
      "category": "graduated",
      "title": "Graduated Board Title 1",
      "content": "This is a graduated board content.",
      "commentCount": 1,
      "imageUrl": null,
      "createdAt": "2024-11-11T21:00:00"
    }
  ]
}
```

2024-11-27 09:45 UTC, mingmingmon approved these changes
피드백 반영 감사합니다! 좋은 작업물로 저도 많이 배워갑니다.

2024-11-27 16:36 UTC, limehee requested changes
인기 게시글 산정 방식에 대해 전략 패턴을 적용해달라고 요청드렸었는데, 현재 코드를 확인해보니 산정 방식뿐만 아니라 요청에 따라 DB에서 데이터를 조회하고 결과를 생성하는 전체 과정을 하나의 전략으로 묶은 것처럼 보여요.
그러나, **인기 게시글 산정 로직 외의 부분은 모든 전략에서 동일하게 동작할 가능성이 높기 때문에**, 산정 로직만을 전략 패턴으로 분리하는 것이 더 적합하다고 판단돼요.
또한, 클래스명이 `DefaultHotBoardService`로 되어 있는데, 일반적으로 전략 패턴을 구현하는 클래스명은 `___Strategy`의 형태를 따르는 경우가 많아요. 클래스명을 더 명확히 변경해주세요.

---

### 요약
1. 전략 패턴은 특정 동작만을 분리하여 캡슐화하는 데 초점이 맞춰져 있어요. 현재 코드는 전략이 과도하게 많은 역할을 맡고 있어요.
2. 게시글 조회나 매핑같은 로직은 산정 방식과 무관하게 모든 전략에서 동일하게 작동할 가능성이 높아요. 이러한 로직은 전략이 아닌 상위 서비스에서 관리되어야 해요.
3. `DefaultHotBoardService`라는 이름은 전략 패턴의 일반적인 명명 규칙(`___Strategy`)에 부합하지 않아요. `DefaultHotBoardStrategy`와 같이 역할이 더 명확히 드러나는 이름으로 변경해주세요.

2024-11-27 16:36 UTC, limehee commented on src/main/java/page/clab/api/domain/community/board/application/service/DefaultHotBoardService.java
> +        LocalDateTime endDate = LocalDate.now().minusWeeks(weeksAgo).with(DayOfWeek.SUNDAY).atTime(23, 59, 59);
이전에 제가 변수명에 대해 `start`와 `end` 뒤에 `date`를 붙이면 좋겠다고 코멘트를 드린 적이 있어요. 해당 코멘트를 반영하시면서 관련된 변수명도 변경하신 것으로 보이는데, 제가 말씀드린 부분은 `findAllWithinDateRange()` 메소드의 파라미터에 대한 요청이었어요. `getHotBoardsForWeek()` 메소드에서는 기존 변수명인 `startOfWeek`, `endOfWeek`이 더 의미를 잘 전달할 수 있다고 생각해요. 해당 부분은 기존 변수명으로 복원하는 것이 더 좋을 것 같습니다.

2024-11-27 16:36 UTC, limehee commented on src/main/resources/messages.properties
> +min.board.size=최소값은 {value} 이상이어야 합니다.
피드백을 반영하는 과정에서 추가된 메시지로 보이지만, 현재 프로젝트에서 사용되지 않고 있어요. 해당 메시지는 제거 부탁드려요.

2024-11-28 12:44 UTC, SongJaeHoonn commented
@limehee 

피드백주신 사항 잘 이해했습니다! 
변수명 변경과 클래스명 변경, 전략 패턴 책임 분리 완료했습니다. 확인 부탁드려요!

그리고 전략 패턴 책임 분리에 관해서는,
저는 전략 패턴을 적용할 때, **다른 요구사항이나 정책이 주어졌을 때 쉽게 갈아 끼울 수 있다는 점**에 초점을 맞췄습니다. 
따라서 인기 게시글을 redis에 저장하도록 리팩토링하기 이전에, 객체지향 5원칙중 개방-폐쇄 원칙(OCP, Open-Closed Principle)을 생각했을 때 클라이언트가 직접 전략을 선택하도록 유도해서 코드의 변경은 확실히 없도록 하되, 확장에는 열려있게 구성했었습니다.
하지만 api 호출 효율에 redis를 사용하는 것의 이점과 전략 패턴에서 인기 게시글 선정시 전략이 과도하게 많은 책임을 가지고 있음을 인정하고, redis를 사용하고 저장과 조회 로직을 분리하도록 리팩토링 완료했습니다.

이렇게 전략의 책임을 분리하고 나니, 컨트롤러에서는 인기게시글 선정과 저장에 관심사를 두는 것이 아니라 redis에서 조회하는 비즈니스 로직에만 연결되어 있기 때문에 인기게시글 선정에 관여할 수 없어, 전략을 수정하려면 `StrategyType`만 수정하면 되긴 하지만, 수정할 부분이 한 줄밖에 안될지라도 결국 백엔드 코드를 고쳐야 하는 OCP 원칙을 위반하는 상황(확장하려면, 코드를 수정해야함)이 발생하게 됩니다.

이런 상황에서는 어떻게 코드를 작성해야 할까요?

2024-12-03 10:01 UTC, SongJaeHoonn commented
@limehee 

상세히 써주신 리뷰와, 좋은 설계 패턴이 담겨있는 프로젝트를 참고용으로 추천해주셔서 정말 감사합니다! 
해당 프로젝트를 둘러보기도 하고, 제안해주신 점들을 적용해보기도 하며 이틀간 많은 고민을 해봤습니다.

하지만,
**1. 전략의 빈 이름을 상수로 관리**
  새로운 전략 생성시 상수로 정의된 클래스에 코드 한 줄을 추가하든, enum에 한 줄을 추가하든 비슷하다고 생각했습니다. 상수 관리를 효율적으로 하기 위해 만들어둔 것이 열거형(enum)이기에 굳이 원시 상태(constants)로 돌아갈 필요가 있나 싶습니다. enum은 각 상수와 관련된 속성과 행동을 정의할 수 있어 가독성 및 유지보수성을 증가시킬 수 있다는 의견입니다. 특히, 필드의 `discription`에 해당 전략의 설명을 자세히 작성할 수 있다는 점이 좋은 것 같아요.

**2. 전략을 Map 형태로 관리**
  저희는 인기게시글을 선정하고, 캐싱하는 로직을 매주 월요일 자정마다 자동으로 스케줄링되도록 계획했습니다. 클라이언트가 월요일 자정마다 선정 api와 같은 것을 호출하지 않는다면 선정에 클라이언트는 관여할 수 없으며, 따라서 `HotBoardRegisterService`에서 Map으로 주입받아 코드 상에서 전략을 고를 수 있도록 구현했었습니다.
이미 전략은 Map 형태로 관리되고 있습니다.

**3. Redis와 전략 연계**
  이 부분을 가장 많이 고민했었는데, 2번의 이유와 같이 선정에 클라이언트가 관여할 수 없으므로 인기게시글 조회에서 클라이언트가 전략을 골라 조회하려면, 월요일 자정마다 미리 모든 전략들을 호출해 redis에 저장해 두어야 하기 때문에, 언제 다시 쓰일지도 모르는(이벤트성 조회 전략) 전략들을 매주 실행시키는 것이 더 효율적이지 않을 것 같다는 생각이 듭니다.

이와 같은 이유들로 코드 수정이 어려웠으며, 예시 들어주신 유사도 계산 알고리즘을 적용하는 프로젝트에서는, 우리의 인기 게시글 기능과는 달리 유사도 계산 및 저장에 클라이언트가 관여할 수 있는 것 같아 이 답글을 작성하는 바입니다..!

2024-12-05 11:16 UTC, limehee commented
@SongJaeHoonn
먼저, 저의 제안에 깊이 고민하고 구체적인 피드백 남겨주셔서 감사하다는 말을 전합니다.

> 1. **전략의 빈 이름을 상수로 관리**
>    새로운 전략 생성시 상수로 정의된 클래스에 코드 한 줄을 추가하든, enum에 한 줄을 추가하든 비슷하다고 생각했습니다.
>    상수 관리를 효율적으로 하기 위해 만들어둔 것이 열거형(enum)이기에 굳이 원시 상태(constants)로 돌아갈 필요가 있나 싶습니다.
>    enum은 각 상수와 관련된 속성과 행동을 정의할 수 있어 가독성 및 유지보수성을 증가시킬 수 있다는 의견입니다. 특히, 필드의 `discription`에 해당 전략의 설명을 자세히 작성할 수 있다는 점이 좋은 것 같아요.

전략명을 상수로 관리하면, 굳이 열거형(enum)을 사용하여 설명을 추가할 필요가 없다고 생각했습니다. 또한, 전략에 따른 동작을 선언할 필요도 없을 것 같다는 판단 하에 이 방법을 제안드렸습니다. 열거형을 사용할 경우 `{전략타입}.{전략}.get_()` 형태로 전략을 명시할 수 있지만, 상수를 사용하면 `{전략타입}.{전략}` 형태로 더 간략하게 표현할 수 있습니다. 하지만, 재훈님의 의견에 따라 추후 전략이 다양해질 것을 고려하여 현재의 열거형을 유지하는 것도 좋은 선택이라고 생각됩니다.

추가로, 현재 전략의 빈 이름이 상수로 관리되지 않고 하드코딩되어 있습니다. 추후 전략 이름이 변경될 경우를 대비하여 `HotBoardSelectionStrategyType.DEFAULT.getKey()`와 같은 형식으로 접근하는 것이 변경 용이성을 높일 수 있을 것으로 보입니다.

```java
@Service("default") // 상수로 변경 필요
@RequiredArgsConstructor
public class DefaultHotBoardSelectionStrategy implements HotBoardSelectionStrategy {
```

---

> 2. **전략을 Map 형태로 관리**
>    저희는 인기게시글을 선정하고, 캐싱하는 로직을 매주 월요일 자정마다 자동으로 스케줄링되도록 계획했습니다.
>    클라이언트가 월요일 자정마다 선정 api와 같은 것을 호출하지 않는다면 선정에 클라이언트는 관여할 수 없으며, 따라서 `HotBoardRegisterService`에서 Map으로 주입받아 코드 상에서 전략을 고를 수 있도록 구현했었습니다.
>    이미 전략은 Map 형태로 관리되고 있습니다.

현재 `HotBoardRegisterService`에서 모든 전략이 Map 형태로 등록되어 있지만, `DEFAULT` 타입으로 고정되어 있는 것을 확인했습니다. 전략 패턴은 특정 행위를 캡슐화하여 동적으로 설정하거나 변경할 수 있도록 하는 것이 핵심입니다. 현재의 코드는 전략 패턴의 본질을 충분히 살리지 못하고 있는 것으로 보입니다.

```java
public void registerHotBoards() {
    HotBoardSelectionStrategy strategy = strategies.get(HotBoardSelectionStrategyType.DEFAULT.getKey()); // DEFAULT 전략으로 고정됨
```

따라서, 이전에 제안드린 대로 클라이언트로부터 인기 게시글 선정 방식을 받아 요청에 따라 다양한 전략을 유동적으로 사용할 수 있도록 설계를 개선하는 것이 더 나은 방향일 것 같습니다.

---

> 3. **Redis와 전략 연계**
>    이 부분을 가장 많이 고민했었는데, 2번의 이유와 같이 선정에 클라이언트가 관여할 수 없으므로 인기게시글 조회에서 클라이언트가 전략을 골라 조회하려면, 월요일 자정마다 미리 모든 전략들을 호출해 redis에 저장해 두어야 하기 때문에, 언제 다시 쓰일지도 모르는(이벤트성 조회 전략) 전략들을 매주 실행시키는 것이 더 효율적이지 않을 것 같다는 생각이 듭니다.

Redis 캐싱과 제가 이전에 제안드린 내용이 상충하는 부분이 있어 위와 같은 코멘트를 남기신 것으로 생각됩니다. 말씀하신 대로 모든 산정 방식을 미리 실행하여 결과를 저장해두는 것은 비효율적입니다.

번거롭겠지만 캐싱 방식을 다음과 같이 변경할 것을 제안드립니다.

- **스케줄링**을 통해 매주 월요일 자정에 Redis에 저장된 모든 캐시 데이터를 삭제합니다.
- **기본(DEFAULT) 전략**만을 실행하여 인기 게시글을 선정하고, 그 결과를 Redis에 저장합니다.
- **기타 전략**은 클라이언트로부터 요청이 들어올 때 실행하여 데이터를 Redis에 캐싱하도록 합니다.

이렇게 변경하면 필요한 시점에만 전략을 실행하고 캐싱함으로써 효율성을 높일 수 있을 것으로 생각됩니다.

---

## 요약
1. **전략 이름 상수 관리**: 열거형을 유지하면서 상수화하여 전략 이름 변경 시 용이하게 대응.
2. **동적 전략 선택**: 클라이언트 요청에 따라 다양한 전략을 유연하게 선택 및 적용.
3. **캐싱 최적화**: 기본 전략은 주기적으로 실행하여 캐싱하고, 기타 전략은 요청 시에만 실행 및 캐싱.

2024-12-13 05:42 UTC, SongJaeHoonn commented
@limehee 
감사합니다! 제안해주신 내용이 작업 방향성에 많은 도움이 되었습니다.
따라서, 제안해주신 방향대로 코드를 리팩토링해보았습니다.

1. **전략 이름 상수 관리**
원래 enum으로 상수를 관리하려고 했으나, enum의 이름이 `HotBoardSelectionStrategies`와 같이 길다는 점, `@Service(상수)`에 enum의 `getKey()`메서드를 사용할 수 없다는 등의 이유에서 enum이 아닌 단순 상수 관리 클래스로 작업하는 것이 좋아보여 열거형 대신 상수 관리 클래스를 사용했습니다.

2. **동적 전략 선택, 캐싱 최적화**
클라이언트가 전략 이름과 함께 요청을 하면, 요청 시 redis key에 해당하는 value(인기 게시글)이 없다면 해당 전략을 이용해 저장 후 조회하고,
이미 캐싱된 인기 게시글이 있다면 바로 조회하도록 변경했습니다.
따라서 월요일 자정마다 `default`전략만을 저장하는  `registerDefaultHotBoards` , 전략 이름을 통해 동적으로 저장할 수 있는 메서드인 `registerHotBoards`로 메서드를 구분했습니다.
그리고 전략 이름이 잘못되거나 없는 전략을 요청할 때에는 `default`전략을 자동 반환하도록 구현했습니다!

2024-12-14 12:25 UTC, limehee reviewed
“HotBoardSelectionStrategies”는 실질적인 도메인 로직보다는 전략 식별용 상수를 모아둔 유틸성 클래스에 가까워서 service 계층 쪽 패키지로 옮겨 관리하는 편이 더 자연스러울 것 같아요.

2024-12-14 20:55 UTC, SongJaeHoonn commented
> “HotBoardSelectionStrategies”는 실질적인 도메인 로직보다는 전략 식별용 상수를 모아둔 유틸성 클래스에 가까워서 service 계층 쪽 패키지로 옮겨 관리하는 편이 더 자연스러울 것 같아요.

뭔가 서비스 계층에서는 비즈니스 로직들만 처리한다는 인식이 있어서 `enum`을 도메인 패키지에 넣듯이 이것도 도메인 패키지에 넣었었는데 꼭 그렇지만은 않는군요

해당 상수들을 service 패키지에서만 이용하다보니 import문이 하나씩 줄어들어서 이런 점에서도 괜찮네요!
수정했습니다.

2024-12-15 03:30 UTC, limehee approved these changes

2024-12-15 06:50 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardSelectionStrategies.java
> +
전략패턴과 OCP 관련해서 많은 고민들을 진행해주신 작업인 것 같습니다! 저도 디자인 패턴 책 읽을 때 가볍게
들어봤던 전략패턴에 대해서 실제로 어떻게 사용할 수 있을 지 알아갈 수 있던 기회였습니다. 제가 @SongJaeHoonn님의 작업을 이해한 게 맞는지 한 번 확인해주시면 감사할 것 같습니다!

1. 추후 새로운 인기 게시글 산정 기준이 생긴다면, 이 부분에 전략 이름을 명시하고, `DefaultHotBoardSelectionStrategy`처럼 새로운 전략을 구현하는 방식일까요? 

2. 다양한 전략들은 모두 `HotBoardSelectionsStrategy`를 implement하기 때문에 Map으로 관리 될 수 있는 것이고, 전략 이름으로 원하는 것을 사용할 수 있는 것인거죠?

2024-12-15 08:26 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/service/HotBoardSelectionStrategies.java
> +
> 추후 새로운 인기 게시글 산정 기준이 생긴다면, 이 부분에 전략 이름을 명시하고, DefaultHotBoardSelectionStrategy처럼 새로운 전략을 구현하는 방식일까요?

정확합니다!

> 다양한 전략들은 모두 HotBoardSelectionsStrategy를 implement하기 때문에 Map으로 관리 될 수 있는 것이고, 전략 이름으로 원하는 것을 사용할 수 있는 것인거죠?

맞습니다.  클라이언트가 파라미터로 전략 이름과 함께 요청하면, `HotBoardSelectionsStrategy`가 전략 이름으로 매핑된 Map에서 전략을 찾아 인기 게시글을 저장(해당 전략으로 저장된 인기게시글이 없을 시)하거나 조회(해당 전략으로 저장된 인기게시글이 있을 시)하게 됩니다.

2024-12-15 11:22 UTC, merged