feat: 개발질문 게시판의 해시태그 기능 구현 완료
kgu-clab/clab-platforms-server pull request #629
Opened 2024-12-15 06:13 UTC by mingmingmon

## Summary

>#609

커뮤니티 게시판 중에서 개발질문 카테고리에 대해서 해시태그를 설정할 수 있는 기능을 개발했습니다.

## Tasks

- 해시태그 등록 API 작성 
(해시태그를 먼저 등록하고, 개발질문 게시판에 해시태그id를 연결하는 형태입니다.)
- 게시글 requestDto에 해시태그id list를 전달하도록 수정 
(개발질문 게시판 전용으로 dto를 만드는 선택지도 있었지만, @Jeong-Ag 님과 회의 후에 결정했습니다. 모든 게시판의 요청 dto에 해시태그 id list를 담아서 전달할 수 있습니다. 이때 null이어도 괜찮습니다. 이는 현재 개발질문 게시판에서만 해시태그 기능을 사용할 수 있지만 추후 확장성을 고려한 선택이었습니다.)
- 게시글 수정 시 해시태그id list를 전달하도록 수정
(게시글을 수정할 때 해시태그 수정도 함께 할 수 있도록 했습니다. 이때는 기존에 있던 해시태그 정보와 새로운 해시태그 정보를 비교해서 소프트 딜리티를 수정하거나 새롭게 등록할 수 있도록 로직을 작성했습니다.)
- 해시태그로 게시글 검색하기
(해시태그를 여러개 전달하면 페이지네이션을 적용해서 해당 해시태그를 모두 포함하는 게시글을 반환합니다.)

## ETC
리뷰 해주실 때 로직에 대한 피드백이나 성능 피드백 많이 해주시면 반영하겠습니다! 다만 수정된 API 연동이 최대한 빨리 진행되어야 해서, **성능 피드백은 PR 머지 후 다른 이슈에서 진행하고자 합니다.** 

## SQL문

**hashtag**
```
CREATE TABLE hashtag (
    id BIGSERIAL PRIMARY KEY,                   
    name VARCHAR(255) NOT NULL,                
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,  
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
```

**BoardHashtag** 
```
CREATE TABLE board_hashtag (
    id BIGSERIAL PRIMARY KEY,                   
    board_id BIGINT NOT NULL,                   -
    hashtag_id BIGINT NOT NULL,                
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,  
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```
## Screenshot

1. 해시태그 생성 API
![image](https://github.com/user-attachments/assets/83bc4093-f27e-4f25-ac0f-205b54ca2827)

2. 개발질문 게시판이 아닌 경우 해시태그 등록 시 예외처리. 해시태그가 없다면 정상 등록 가능.
![image](https://github.com/user-attachments/assets/613998fd-1ef4-446d-9a18-8c496ea05a62)
![image](https://github.com/user-attachments/assets/0598aba1-3602-45be-84ee-50193dae7e9a)

3. 게시글 상세조회 API에서 해시태그 정보를 함께 반환하도록 수정함. 해시태그가 없는 경우는 빈 리스트를 반환. 다른 게시글 조회 관련 API도 마찬가지로 수정완료.
![image](https://github.com/user-attachments/assets/86f9c3dd-afb2-4347-bc3d-e00d40db16dc)
![image](https://github.com/user-attachments/assets/f0815a27-f9ab-4cae-96fe-d1bfa73122cd)

4. 게시글 수정 API에서 해시태그 정보를 받도록 수정. 이때 카테고리가 개발질문인 것만 해시태그 정보를 수정가능하도록 예외처리
![image](https://github.com/user-attachments/assets/3983113c-d553-40cb-8764-0e6e27516dfe)

5. 해시태그가 모두 포함된 게시글 조회
[자료구조 해시태그]
![image](https://github.com/user-attachments/assets/58a6b679-05d6-4f6e-abcf-358522b8999f)
[JAVA, C++ 해시태그]
![image](https://github.com/user-attachments/assets/0952ccf6-b6ad-4a0e-832c-b548d129b80d)

2024-12-16 10:00 UTC, limehee commented on src/main/java/page/clab/api/domain/community/hashtag/adapter/in/web/HashtagRegisterController.java
> +    @Operation(summary = "[U] 해시태그 생성", description = "ROLE_USER 이상의 권한이 필요함")
현재 해시태그는 운영진 및 코어팀과 사전 협의된 내용으로 구성되는 것으로 알고 있어요. 혹시 제가 잘못 인지한 것일까요? 만약 해시태그 생성 권한을 일반 사용자에게 허용한다면, 서버의 공격 표면이 증가하고 불필요한 데이터가 생성될 가능성이 높아 보여요.

2024-12-16 10:02 UTC, limehee commented on src/main/java/page/clab/api/domain/community/hashtag/domain/Hashtag.java
> +    String name;
해시태그의 중복 등록을 방지하기 위해 유니크 제약 조건을 추가하는 것이 필요해 보여요.

2024-12-16 10:02 UTC, limehee commented on src/main/java/page/clab/api/external/community/board/application/port/ExternalRetrieveBoardHashtagUseCase.java
> +    List<BoardHashtagResponseDto> getBoardHashtagInfoByBoardId(Long boardId);
`{`와 메소드 선언부 사이에 개행이 누락되었어요.

2024-12-16 10:04 UTC, limehee commented on src/main/java/page/clab/api/external/community/board/application/service/ExternalBoardHashtagRegisterService.java
> +            };
해당 내용은 `getById()` 메소드를 추가로 작성하여, `PersistenceAdapter`에서 담당하도록 하는게 책임 분리에 더욱 적합해 보여요.

2024-12-16 10:05 UTC, limehee commented on src/main/java/page/clab/api/external/hashtag/application/port/ExternalRetrieveHashtagUseCase.java
> +    Hashtag getById(Long id);
`{`와 메소드 선언부 사이에 개행이 누락되었어요.

2024-12-20 04:59 UTC, SongJaeHoonn requested changes
작업량이 정말 많으셨을 것 같은데, 빠르게 진행해주신 것 같아 놀랐습니다! 고생하셨습니다.

일단, 저는 해시태그에 대해 그냥 `List<String>`으로 관리하고, Board를 저장할 때에도 `String`으로 받아  개발 질문 게시글에 대해서만 반환하도록 하는 걸로 간단하게 생각했었는데, `Hashtag`라는 새로운 도메인을 만드실 줄은 몰랐습니다..! 
`HashTag` 엔티티를 사용하는게 아니라 그냥 `String`으로만 관리하면 간단할 것 같은데 `Hashtag` 도메인을 새로 구현하신 이유가 있으신지 궁금합니다.

2024-12-20 04:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardHashtagPersistenceAdapter.java
> +    public List<BoardHashtag> getAllByBoardId(Long boardId) {
이전에 코드베이스 전반 검토할 때, `findBy`는 예외처리를 하지 않고 조회하는 메서드, `getBy`는 예외처리까지 포함되어 조회하는 메서드에 적용하기로 했어서, 작업하신 메서드 이름들을 올바른 이름으로 바꾸는 작업이 필요할 것 같아요.

2024-12-20 04:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardHashtagRepositoryImpl.java
> +    private final JPAQueryFactory queryFactory;
동감입니다.

2024-12-20 04:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/dto/mapper/BoardHashtagDtoMapper.java
> +    public BoardHashtagRequestDto toDto(Long boardId, List<Long> hashtagIdList) {
`List<Long> hashtagIdList` -> `List<Long> hashtagIds`
저희 프로젝트에서 리스트를 변수로 표현할 때 뒤에 `List`를 붙이는 게 아니라 복수형으로 표현하는 것으로 알고있어서 변경 제안 드립니다.

2024-12-20 04:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/service/BoardRegisterService.java
> +            externalRegisterBoardHashtagUseCase.registerBoardHashtag(boardHashtagDtoMapper.toDto(savedBoard.getId(), requestDto.getHashtagIdList()));
제가 잘못 이해하고 있는건지는 모르겠지만, 굳이 `BoardHashtag` 등록을 external에서 끌고와서 해야 하는지 모르겠습니다.
`Board`도메인 안에서 처리가 불가능한 것인가요?

2024-12-20 04:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/service/BoardRegisterService.java
> +            externalRegisterBoardHashtagUseCase.registerBoardHashtag(boardHashtagDtoMapper.toDto(savedBoard.getId(), requestDto.getHashtagIdList()));
`Board` 도메인 내에서 `BoardHashtag`의 저장 및 조회를 `externalRegisterBoardHashtagUseCase`, `externalRetrieveBoardHashtagUseCase`를 통해 수행하고 있는 것 같은데, `Board`도메인의 서비스 계층에서 담당해도 괜찮지 않을까 생각합니다.

2024-12-20 04:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/service/BoardUpdateService.java
> +        hashtagsToAdd.forEach(idToAdd -> addHashtag(board.getId(), idToAdd, currentBoardHashtags));
`BoardHashtag`를 업데이트하는 주요 비즈니스 로직인데, 메서드 하나에 너무 많은 로직이 들어가 있기도 하고, 인덴트도 깊어서 보기 힘들거나 이해하는데 오랜 시간이 소요될 수 있을 것 같아요. 
인덴트가 깊거나 한 줄이 너무 긴 부분은 메서드로 추출해서 로직의 흐름을 한 눈에 파악할 수 있도록 하는 것도 괜찮아 보입니다.

2024-12-20 04:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/hashtag/adapter/in/web/HashtagRegisterController.java
> +    @Operation(summary = "[U] 해시태그 생성", description = "ROLE_USER 이상의 권한이 필요함")
제가 생각했을 때에는 `velog`에서 해시태그를 추가할 때처럼, 사용자가 직접 본인만의 해시태그를 만들어서 추가하는 방식으로 하면 원하는 해시태그가 없을 때에도 손쉽게 추가할 수 있어 자유도가 증가할 것이라고 생각했는데, 
블로그의 게시글과 커뮤니티 게시글의 특성이 다르다보니 해시태그가 악용될 수 있다는 생각도 들긴 하네요.

2024-12-20 04:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/hashtag/application/dto/mapper/HashtagDtoMapper.java
> +    public Hashtag fromDto(String name) {
이부분은 Dto에서 `Hashtag`를 생성하는 것이 아니기 때문에 메서드 이름을 `of`로 해야 맞을 것 같아요.

2024-12-20 04:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/hashtag/application/port/in/RetrieveHashtagUseCase.java
> +public interface RetrieveHashtagUseCase {
개행이 필요할 것 같습니다.

2024-12-20 04:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/hashtag/application/port/out/RegisterHashtagPort.java
> +
개행을 하지 않아도 될 것 같습니다.

2024-12-20 05:13 UTC, limehee commented on src/main/java/page/clab/api/domain/community/hashtag/adapter/in/web/HashtagRegisterController.java
> +    @Operation(summary = "[U] 해시태그 생성", description = "ROLE_USER 이상의 권한이 필요함")
지금은 정해진 태그로 필터링하는 형식으로 기획되어있어서, 권한은 나중에 풀어도 괜찮을 것 같아요.

2024-12-20 13:54 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/community/hashtag/adapter/in/web/HashtagRegisterController.java
> +    @Operation(summary = "[U] 해시태그 생성", description = "ROLE_USER 이상의 권한이 필요함")
기획 단계에서 해시태그는 velog와 동일하게 사용자가 직접 생성하는 것으로 만들 수 있는 것으로 알고 있었습니다!

따라서 해시태그 등록 API를 만들었고, 따로 사용할 수 있는 해시태그를 ENUM으로 관리하고 있지 않았어요.

보안적으로 크게 문제가 될 수 있다면 프론트 분들과 다시 한 번 이야기해도 괜찮을까요?

2024-12-21 10:53 UTC, mingmingmon commented
@limehee @SongJaeHoonn 두 분의 피드백 감사합니다!

- 코드 컨벤션 부분은 특이사항 없이 수정하도록 하겠습니다. 

- 두 분께서 해시태그 설계에 대해서 좋은 의견을 내주셔서 프론트엔드 담당자 @Jeong-Ag님과 이야기 나눠보고, 제 나름대로 내린 설계 방향에 대해서 추가로 설명 드리도록 하겠습니다. 아래의 내용 읽어보시고 또 의견 주시면 감사하겠습니다!
----------------------

1.  @SongJaeHoonn님이 제안해주신 HashTag 엔티티 대신 `List<String>`으로 Board 마다 저장을 한다면 **해시태그를 저장하고 조회하는 행위는** 구현이 쉬워지는 것이 맞습니다. 이 방법을 작업 초반에 고려를 해보았는데요. 결국 HashTag 엔티티를 추가하는 쪽으로 결정된 이유는 아래와 같습니다.

- 같은 해시태그의 중복 저장 가능성
`List<Stirng>`을 사용할 경우 같은 해시태그가 중복해서 저장될 가능성이 존재합니다. `Set<String>`을 사용할 수도 있다고 생각이 들었지만, Set도 아래의 문제를 해결하기 부족하다고 생각해서, 테이블 설계를 선택했습니다.

- 해시태그별 게시글 조회 성능의 비효율성
이번 해시태그 기능으로 개발 질문 게시판에 한해, 1개 이상의 해시태그를 선택하게 되면 그 해시태그가 모두 포함된 게시글을 반환하는 기능이 추가됩니다. 만약 `List<String>`으로 Board에게 hashtag 들을 관리하도록 한다면, 해시태그 기준 조회 시 전체 게시글을 순회하면서 각각의 `List<String>`을 살펴봐야 합니다. 
이 방식보다는 HashTag 엔티티를 두고, BoardHashTag 테이블에서 게시글과 해시태그 간의 매핑을 확인해서 조회하는 것이 효율적이라고 판단했습니다. 이러한 **RDBMS 활용의 장점을 극대화하기 위해서 제가 적용하지 않았던 인덱싱을 추가** 하도록 하겠습니다.

- blue-green 배포 시 데이터 손실의 위험성
우선 저는 `List<String>` 방식이나 `Set<String>` 방식으로 해시태그를 저장한다는 것을, DB에 저장을 하지 않는 것으로 이해했습니다. 이렇게 되면 우리 서비스에서 사용하고 있는 무중단 배포 시에 어플리케이션 메모리에 저장된 데이터 (`List<String>`, `Set<String>`으로 저장한 board들의 해시태그들)은 서비스가 종료될 때 소멸할 것입니다. 이러한 문제를 해결하기 위해서는 결국 `@ElementCollection`이나 해시태그 정보를 JSON으로 칼럼에 저장하는 등의 방식을 사용해야할 수 있을 거에요. **그렇게 되면 결국 DB에 저장한다는 행위가 필수적**이기에 HashTag와 BoardHashTag 엔티티를 사용하는 것이 좋다고 생각했습니다.
----------------------------------
2. @SongJaeHoonn 님이 Board 도메인에서 해시태그 등록을 바로 처리할 수 있지 않을까? 라는 설계적 조언을 해주셨어요. 지금 제가 구현한 상태는 이해하신 것처럼 BoardHashtag 등록을 external로 분리해서 BoardRegisterService에서 참조하도록 하고 있는게 맞습니다! 제가 external로 추출한 이유는 아래와 같습니다.

- 도메인 객체를 분리? 도메인을 분리?
저는 external 패키지를 다른 도메인 객체에 작업을 시도해야 할 때 external로 필요한 부분을 뽑아서 참조할 수 있는 것으로 이해했어요. 따라서 BoardHashtag와 Board도 다른 도메인으로서 독립적으로 처리를 해야 된다고 생각했답니다. 그렇지만 @SongJaeHoonn 님의 제안과 external의 다른 usecase들을 참고해 보니, **도메인 객체가 아닌 context bound에 해당하는 도메인이 다를 경우 external로 뽑아서 처리**하더라구요. external에 대한 정확한 이해가 이게 맞을까요? 그렇다면 제가 Board 내에서 boardHashtag를 등록하도록 수정하는 것이 맞는 것 같습니다!
(비교대상으로 hashtag의 경우는 board 도메인과 분리되어 있기 때문에 external로 빼야하고, boardHashtag는 board에 종속되어 있기 때문에 external로 빼지 않아도 된다고 이해했습니다.)
----------------------------------

3. @limehee님께서 짚어주신 해시태그 자율 생성과 보안 문제에 대해서 궁금한 점과 @Jeong-Ag 님과 이야기했던 내용을 바탕으로 추가적으로 구성해본 설게 방식에 대해 설명드릴게요!

- 보안 위협에 대한 궁금증
해시태그를 사용자가 필요에 따라 자유롭게 생성하는 것이 공격표면을 넓힐 수 있다고 이야기해주셨어요. 제가 예상한 범위는, 기본적인 SQL Injection이나 Xss, 대량의 스팸 데이터 정도 였습니다. **만약 이러한 부분이 공격 지점이 될 수 있다면, 다른 POST 형태의 API도 위협이 될 것으로 생각**했어요. 해시태그 자율 등록이 가지는 새로운 보안 위협이 있을까요? 보안 공격을 대처할 수 있는 방식으로 구현할 수 있는 방법은 없는걸까요? 
보안 위협을 예방하기 위해 새로운 기능이나 시도가 제약되는 것 같아서 혹시 예방법이 있다면 그런 쪽으로 풀어나가는 것도 좋을 것 같아서 여쭤봅니다! 제가 아직 보안적 관점이 부족해서 @limehee 님이 짚어주신 보안 취약점에 대해서 조금 더 설명 부탁드립니다!

- 고정된 해시태그를 사용할 경우 Enum으로? 또는 테이블로?
제가 위의 질문을 가지면서 한편으로는, @limehee 님이 짚어주신 사용자의 해시태그 자율 생성이 아닌, 해시태그를 정해놓고 등록할 수 있는 방안에 대해서도 @Jeong-Ag 님과 이야기 했었습니다. 그 결과 아래와 같이 선정이 되었는데요.
```
(C, C++, Java, Javascrip, Python, Assembly, Kotlin, Typescript)
(Front-end, Back-end, AI, Game, Android, IOS)
(DB, Devops, Infra, framwork, algorithm)
(기타)
``` 

이러한 해시태그를 고정으로 둔다면 Enum으로 관리하는 것이 가장 먼저 떠올랐습니다. 그렇지만 만약, 해시태그를 추가적으로 등록하거나 삭제하는 경우에서는 프론트와 백에서 매번 Enum을 수정해야 된다고 생각했어요. 그래서 저는 **위에서 선정된 해시태그들을 지금 구현된 HashTag 테이블에 저장하고, 추가 삭제의 경우는 ADMIN 권한만 가능하도록 하면 유지보수가 편하다고 생각**했습니다. 이 설계에 대해서 어떻게 생각하시는지 궁금합니다!

----------------
설계 부분을 고민하다보니 글이 많이 길어졌습니다,, 부족한 부분 있으면 바로 피드백 주세요!

2024-12-21 11:07 UTC, limehee commented on src/main/java/page/clab/api/domain/community/hashtag/adapter/in/web/HashtagRegisterController.java
> +    @Operation(summary = "[U] 해시태그 생성", description = "ROLE_USER 이상의 권한이 필요함")
처음부터 사용자가 게시글에 해시태그를 자유롭게 생성할 수 있도록 서비스를 제공하고 프론트엔드에서 이를 적절히 처리한다면 큰 문제가 되지 않을 것 같아요. 다만, 더 이상 사용되지 않는 해시태그에 대해서는 적절한 관리가 필요할 것 같아요.

2024-12-21 11:26 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardHashtagRepositoryImpl.java
> +    private final JPAQueryFactory queryFactory;
다른 customRepositoryImpl(`JobPostingRepositoryImpl` 또는`ApplicationRepositoryImpl`)에서는 QeuryDSL에서 제공하고 있는 `BooleanBuilder`를 대부분 사용해서 다양한 조건을 동적으로 처리하는 것으로 알고 있습니다. 

제가 이번에 작성하게 된 쿼리문은 위의 customRepositoryImpl와 다르게 단순히 List<Long> hashtagIds를 가지고 필터링 하면서(고정적 조건) distinct나 groupby, having 등의 구문에 힘을 주는 경우였습니다. 따라서 직관적으로 SQL과 유사한 형식으로 작성회는 JPQL을 선택했습니다. 

```
@Query("SELECT DISTINCT b.boardId " +
           "FROM BoardHashtagJpaEntity b " +
           "WHERE b.hashtagId IN :hashtagIds " +
           "AND b.isDeleted = false " +
           "GROUP BY b.boardId " +
           "HAVING COUNT(b.hashtagId) = :size")
    List<Long> getBoardIdsByHashTagId(@Param("hashtagIds") List<Long> hashtagIds, @Param("size") Long size, Pageable pageable);
}
```
위와 같이 `@Query`를 사용할 수 있다면 customRepositoryImpl에서 구현하지 않고 바로 일반 Repository에서 구현하는 편이 프로젝트의 일관성에 더 좋을까요?? 쿼리문이 길어짐에 따라 가독성이 떨어지는 문제 때문에 Impl를 사용해보려고 했는데 위의 다른 코멘트에서 언급해주신 것처럼 개행으로 처리하면 괜찮아 보일까요?

2024-12-21 12:00 UTC, limehee commented
> * 보안 위협에 대한 궁금증
>   해시태그를 사용자가 필요에 따라 자유롭게 생성하는 것이 공격표면을 넓힐 수 있다고 이야기해주셨어요. 제가 예상한 범위는, 기본적인 SQL Injection이나 Xss, 대량의 스팸 데이터 정도 였습니다. **만약 이러한 부분이 공격 지점이 될 수 있다면, 다른 POST 형태의 API도 위협이 될 것으로 생각**했어요. 해시태그 자율 등록이 가지는 새로운 보안 위협이 있을까요? 보안 공격을 대처할 수 있는 방식으로 구현할 수 있는 방법은 없는걸까요?
>   보안 위협을 예방하기 위해 새로운 기능이나 시도가 제약되는 것 같아서 혹시 예방법이 있다면 그런 쪽으로 풀어나가는 것도 좋을 것 같아서 여쭤봅니다! 제가 아직 보안적 관점이 부족해서 @limehee 님이 짚어주신 보안 취약점에 대해서 조금 더 설명 부탁드립니다!

프론트 팀과 별도로 진행된 논의 내용은 제가 공유받지 못하여 정확히 알지 못합니다. 그러나 제가 이해한 바에 따르면, 해시태그 기능은 사용자가 카테고리 게시판에서 해시태그를 선택하면 해당 해시태그로 등록된 게시글 목록이 표시되는 방식입니다. 이 경우, 일부 사용자가 권한 관리가 적절히 이루어지지 않는 점을 악용하여 다량의 해시태그를 생성할 수 있으며, 이로 인해 더미 해시태그가 페이지에 노출될 수 있습니다. 또한, API 요청에 제한이 없을 경우 시스템 부하가 증가하여 서비스에 영향을 미칠 수 있으며, 최악의 경우 무작위로 생성된 데이터로 인해 저장 공간이 부족해지는 등의 문제가 발생할 수 있습니다.

물론, 민주님께서 언급하신 대로 다른 `POST` 메소드의 API도 유사한 문제가 발생할 수 있다는 점은 일리 있지만, 적절한 권한 제어를 통해 공격 가능성을 최소화하고 서비스 이용자에게 미치는 영향을 줄이는 것이 중요하다고 생각합니다. 따라서 해시태그 자율 생성으로 인한 보안 취약점을 예방하기 위한 추가적인 방안이 필요하다고 판단됩니다.

---

> * 고정된 해시태그를 사용할 경우 Enum으로? 또는 테이블로?
>   제가 위의 질문을 가지면서 한편으로는, @limehee 님이 짚어주신 사용자의 해시태그 자율 생성이 아닌, 해시태그를 정해놓고 등록할 수 있는 방안에 대해서도 @Jeong-Ag 님과 이야기 했었습니다. 그 결과 아래와 같이 선정이 되었는데요.
> 
> ```
> (C, C++, Java, Javascrip, Python, Assembly, Kotlin, Typescript)
> (Front-end, Back-end, AI, Game, Android, IOS)
> (DB, Devops, Infra, framwork, algorithm)
> (기타)
> ```
> 
> 이러한 해시태그를 고정으로 둔다면 Enum으로 관리하는 것이 가장 먼저 떠올랐습니다. 그렇지만 만약, 해시태그를 추가적으로 등록하거나 삭제하는 경우에서는 프론트와 백에서 매번 Enum을 수정해야 된다고 생각했어요. 그래서 저는 **위에서 선정된 해시태그들을 지금 구현된 HashTag 테이블에 저장하고, 추가 삭제의 경우는 ADMIN 권한만 가능하도록 하면 유지보수가 편하다고 생각**했습니다. 이 설계에 대해서 어떻게 생각하시는지 궁금합니다!

초기 논의된 방향을 그대로 적용할 경우, 해시태그를 `Enum` 또는 `String` 타입으로 관리하는 것 모두 큰 문제는 없을 것으로 보입니다. `Enum`을 사용하면 안정성과 관리 측면에서 분명한 장점이 있지만, 가까운 미래에 velog 서비스와 유사한 형식으로 변경되거나 해시태그가 자주 변경될 예정이라면 마이그레이션 과정과 부수적인 코드 수정이 번거로울 수 있습니다. 반면, `String` 타입을 사용할 경우 프론트 팀과의 협업 하에 고정된 해시태그를 사용하는 경우, 잘못된 해시태그 요청에 대한 모니터링이 필요할 것입니다. 또한, 중복되는 해시태그의 관리와 더 이상 사용되지 않는 해시태그의 체계적인 관리가 필요합니다.

저는 민주님께서 언급하신 대로 현재 구현된 `HashTag` 테이블에 고정된 해시태그를 저장하고, 추가 또는 삭제가 필요할 경우 `ADMIN` 권한을 통해서만 가능하도록 하는 방안이 유지보수 측면에서 효율적이라고 생각합니다. 이러한 설계는 프론트와 백엔드 간의 `Enum` 수정 없이 유연하게 해시태그를 관리할 수 있으며, 필요 시 관리자의 권한 하에 해시태그를 체계적으로 관리할 수 있는 장점이 있습니다.

2024-12-21 14:26 UTC, SongJaeHoonn commented
> * 같은 해시태그의 중복 저장 가능성
>   `List<Stirng>`을 사용할 경우 같은 해시태그가 중복해서 저장될 가능성이 존재합니다. `Set<String>`을 사용할 수도 있다고 생각이 들었지만, Set도 아래의 문제를 해결하기 부족하다고 생각해서, 테이블 설계를 선택했습니다.

이 부분은 서비스단에서 게시글 저장시 해당 게시글에 대한 중복 검증 절차를 거치면 괜찮을 것이라고 생각했습니다. 
그러나, 

> * 해시태그별 게시글 조회 성능의 비효율성
>   이번 해시태그 기능으로 개발 질문 게시판에 한해, 1개 이상의 해시태그를 선택하게 되면 그 해시태그가 모두 포함된 게시글을 반환하는 기능이 추가됩니다. 만약 `List<String>`으로 Board에게 hashtag 들을 관리하도록 한다면, 해시태그 기준 조회 시 전체 게시글을 순회하면서 각각의 `List<String>`을 살펴봐야 합니다.
>   이 방식보다는 HashTag 엔티티를 두고, BoardHashTag 테이블에서 게시글과 해시태그 간의 매핑을 확인해서 조회하는 것이 효율적이라고 판단했습니다. 이러한 **RDBMS 활용의 장점을 극대화하기 위해서 제가 적용하지 않았던 인덱싱을 추가** 하도록 하겠습니다.

이 부분에서 제가 해시태그 기반 게시글 반환 기능이 있다는걸 인지하지 못했네요. 말씀해주신대로, 조회 시 전체 게시글을 순회하는 패턴은 효율이 많이 떨어지고, `HashTag`도메인 없이 단순 String으로 저장하는 방식은 DB를 효과적으로 이용할 수 없고 `@ElementCollection`의 사용보다는 새로운 엔티티 설계가 더 좋았을 것 같네요! 자세히 설명해주셔서 감사합니다.

---


> * 도메인 객체를 분리? 도메인을 분리?
>   저는 external 패키지를 다른 도메인 객체에 작업을 시도해야 할 때 external로 필요한 부분을 뽑아서 참조할 수 있는 것으로 이해했어요. 따라서 BoardHashtag와 Board도 다른 도메인으로서 독립적으로 처리를 해야 된다고 생각했답니다. 그렇지만 @SongJaeHoonn 님의 제안과 external의 다른 usecase들을 참고해 보니, **도메인 객체가 아닌 context bound에 해당하는 도메인이 다를 경우 external로 뽑아서 처리**하더라구요. external에 대한 정확한 이해가 이게 맞을까요? 그렇다면 제가 Board 내에서 boardHashtag를 등록하도록 수정하는 것이 맞는 것 같습니다!

패키지로 나뉘어진 도메인(`Board`, `Member`, `Comment`)에서 다른 도메인을 참조해야 하면 external로 빼는 것은 현재 아키텍처 구조에서는 당연한 것 같습니다. 그러나 같은 도메인 내에서 각 도메인 객체(entity)를 다룰 때에는 해당 도메인 안에서 처리를 하는 것이 맞다고 생각해요.

>   (비교대상으로 hashtag의 경우는 board 도메인과 분리되어 있기 때문에 external로 빼야하고, boardHashtag는 board에 종속되어 있기 때문에 external로 빼지 않아도 된다고 이해했습니다.)

정확하게 이해하셨습니다!

2024-12-22 08:49 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/community/hashtag/domain/Hashtag.java
> +    String name;
해당 부분은 domain/Hashtag에 위치해있어서 따로 유니크 제약 조건을 넣지 않았고, 영속성 객체에서 아래와 같이 유니크 조건을 명시했습니다!

```
public class HashtagJpaEntity extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "name", unique = true, nullable = false)
    private String name;

    @Column(name = "is_deleted", nullable = false)
    private Boolean isDeleted;
}


```

2024-12-22 10:18 UTC, mingmingmon commented
1. external로 빠져있던 boardHashtag 관련된 로직을 board 패키지 아래로 옮겼습니다.
2. 해시태그를 사용할 수 있는 카테고리인지 확인하는 로직을 보충했습니다.
3. Hashtag 테이블에 해시태그를 저장하고 조회할 수 있는 API를 작성했습니다. 이때 boardUsage라는 필드를 통해서 해당 해시태그가 게시글에서 몇 번 쓰였는지 알 수 있도록 했습니다. 아래 사진처럼 뷰를 만들기 위해 추가된 필드입니다.
![image](https://github.com/user-attachments/assets/f9f149d2-979f-422d-9099-fa35fb5070a4)
4. service가 아닌 도메인 객체에서 처리할 수 있는 검증 로직을 DDD에 맞게 수정했습니다.
5. 복잡한 로직과 stream 사용으로 인한 가독성 저하를 메소드 추출로 개선했습니다.

2024-12-22 10:46 UTC, mingmingmon commented
최종 SQL문 입니다.
```

CREATE TABLE hashtag (
    id BIGSERIAL PRIMARY KEY,                
    name VARCHAR(255) NOT NULL,                  
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,  
    board_usage BIGINT DEFAULT 0 NOT NULL,     
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL 
);
```

```

CREATE TABLE board_hashtag (
    id BIGSERIAL PRIMARY KEY,                  
    board_id BIGINT NOT NULL,                   
    hashtag_id BIGINT NOT NULL,                  
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,  
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL  
);

CREATE INDEX idx_board_hashtag_board_id ON board_hashtag (board_id);
CREATE INDEX idx_board_hashtag_hashtag_id ON board_hashtag (hashtag_id);

```

```

INSERT INTO hashtag (name, is_deleted, board_usage, created_at, updated_at) VALUES
('C', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C++', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Java', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Javascript', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Python', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Assembly', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kotlin', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Typescript', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Front-end', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Back-end', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AI', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Game', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Android', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('IOS', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DB', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Devops', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Infra', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('framework', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('algorithm', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('기타', false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

```

2024-12-23 06:40 UTC, SongJaeHoonn reviewed
제안했던 내용 잘 반영해주셔서 감사합니다! 추가적인 코멘트 남깁니다.

2024-12-23 06:40 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardHashtagRepository.java
> +            "GROUP BY b.boardId " +
DISTINCT와 GROUP BY가 둘 다 중복 제거가 되는 것으로 알고 있습니다.
GROUP BY만 사용함으로써 쿼리 성능을 향상시키는 것도 좋을 것 같아요.

2024-12-23 06:40 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardHashtagRepository.java
> +            "HAVING COUNT(b.hashtagId) = :size")
`HAVING COUNT(b.hashtagId) = SIZE(:hashtagIds)` 이런식으로 long 타입의 size를 직접 가져오지 말고 쿼리에서 실행시키는건 어떨까요?

2024-12-23 06:40 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/application/service/BoardRegisterService.java
>          if (savedBoard.isDevelopmentQna() && requestDto.getHashtagIdList() != null) {
이미 `board.validateBoardHashtagRegistration`으로 검증을 했는데 한번 더 검증을 하는 과정이 불필요할 것 같다는 생각입니다.

2024-12-23 06:40 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/domain/Board.java
> +    public void validateBoardHashtagRegistration(List<Long> hashtagIdList) {
다른 곳은 `hashtagIds`로 되어있어서,  여기서도 `hashtagIdList`말고 `hashtagIds`로 통일하는 게 좋을 것 같습니다 !

2024-12-23 06:52 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardHashtagRepository.java
> +            "GROUP BY b.boardId " +
DISTINCT와 GROUP BY가 둘 다 중복 제거가 되는 걸로 알고있어서, GROUP BY만 사용해도 괜찮을 것 같다는 생각입니다.

2024-12-23 06:52 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardHashtagRepository.java
> +            "HAVING COUNT(b.hashtagId) = :size")
size 계산할 때 파라미터로 불러오지 말고, SQL문 안에서 다음과 같이 작성해 쿼리에서 사이즈 계산을 담당하도록 하는건 어떤가요?
`HAVING COUNT(b.hashtagId) = SIZE(:hashtagIds)`

2024-12-23 09:29 UTC, limehee commented on src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardHashtagRepositoryImpl.java
> +    private final JPAQueryFactory queryFactory;
민주님의 의견에 동감하고, 구체적으로 설명해주셔서 감사합니다.
일반적으로 JPQL을 위해 별도의 인터페이스나 구현체를 새로 작성하지 않는 것으로 알고 있어요. 작성해주신 예제 코드처럼 적절히 개행을 추가해 가독성을 높이는 방향이 좋을 것 같네요.

2024-12-23 09:57 UTC, limehee commented on src/main/java/page/clab/api/domain/community/hashtag/domain/Hashtag.java
> +    String name;
반영 감사합니다.

2024-12-23 10:10 UTC, limehee approved these changes
재훈님이 추가로 남겨주신 코멘트만 해결하면 될 것 같습니다. 긴 시간 작업하시느라 고생 많으셨어요.

2024-12-24 08:51 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardHashtagRepository.java
> +            "HAVING COUNT(b.hashtagId) = :size")
오 감사합니다! (long)으로 타입캐스팅을 해야했는데 이 방식이 더 적합한 것 같습니다!

2024-12-24 09:03 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardHashtagRepository.java
> +            "HAVING COUNT(b.hashtagId) = :size")
다만 방금 로컬환경에서 실행해보니 아래와 같은 오류가 발생했습니다.

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accusationReportService' defined in file [C:\0.git\C-Lab_Core_Team_Server\build\classes\java\main\page\clab\api\domain\community\accuse\application\service\AccusationReportService.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'externalBoardRetrievalService' defined in file [C:\0.git\C-Lab_Core_Team_Server\build\classes\java\main\page\clab\api\external\community\board\application\service\ExternalBoardRetrievalService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'boardRetrievalService' defined in file [C:\0.git\C-Lab_Core_Team_Server\build\classes\java\main\page\clab\api\domain\community\board\application\service\BoardRetrievalService.class]: Unsatisfied dependency expressed through constructor parameter 3: Error creating bean with name 'boardHashtagRetrieveService' defined in file [C:\0.git\C-Lab_Core_Team_Server\build\classes\java\main\page\clab\api\domain\community\board\application\service\BoardHashtagRetrieveService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'boardHashtagPersistenceAdapter' defined in file [C:\0.git\C-Lab_Core_Team_Server\build\classes\java\main\page\clab\api\domain\community\board\adapter\out\persistence\BoardHashtagPersistenceAdapter.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'boardHashtagRepository' defined in page.clab.api.domain.community.board.adapter.out.persistence.BoardHashtagRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Could not create query for public abstract java.util.List page.clab.api.domain.community.board.adapter.out.persistence.BoardHashtagRepository.getBoardIdsByHashTagId(java.util.List); Reason: Validation failed for query for method public abstract java.util.List page.clab.api.domain.community.board.adapter.out.persistence.BoardHashtagRepository.getBoardIdsByHashTagId(java.util.List)
```

내용을 요약하자면, 재훈님이 제안해주신대로 size를 사용할 경우 SQL문 생성이 불가하다고 합니다.

해당 오류의 이유에 대해서 찾아보니 아래와 같은 결론을 찾을 수 있었습니다.

1. SIZE() 사용이 가능한 경우는 엔티티 내부에 정의된 `@OneToMany, @ManyToMany`와 같은 컬렉션 필드의 크기를 구할 때입니다. 
2. 따라서 SIZE(:파라미터)의 형태인 JPQL 외부에서 전달되는 값은 데이터베이스 테이블과 직접 연결되어 있지 않기 때문에 JPQL이 값의 크기를 계산할 수 없습니다.

따라서 이전 방식대로 컬렉션의 크기를 구해서 JPQL에 전달해주어야 할 것 같습니다! 혹시 제가 잘못 이해한 것이라면 추가 설명 부탁드려요.

2024-12-25 04:12 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardHashtagRepository.java
> +            "HAVING COUNT(b.hashtagId) = :size")
앗.. 테이블과 연결되어 있지 않는건 생각하지 못했네요
오류의 이유까지 설명해주셔서 감사합니다. 또 하나 배워갑니다!

2024-12-25 04:12 UTC, SongJaeHoonn approved these changes

2024-12-26 09:16 UTC, merged