feat: 운영진 관리 기능 구현 완료
kgu-clab/clab-platforms-server pull request #648
Opened 2024-12-28 08:52 UTC by SongJaeHoonn

## Summary

> #642 

효율적인 운영진 정보 관리를 위해, 운영진 CRUD를 구현했습니다.

## Tasks

- 운영진 등록 기능
- 운영진 조회 기능
- 운영진 수정 기능
- 운영직 삭제 기능

## ETC

- `MemberManagement` 카테고리의 `Executive` 도메인을 새로 만들었습니다.

- 현재 `Member` entity처럼, PK가 학번인 경우 그 값은 고유하고 변경되지 않기 때문에 `Executive`의 PK도 학번(id)으로 설정했으며, 이 값은 변경할 수 없도록 했습니다.

- 운영진 직급을 회장,부회장과 같은 문자열로 처리하려고 했으나, 유지보수의 용이성을 위해 `Enum`으로 관리하도록 했습니다.

- 정렬 순서는 PRESIDENT -> VICE_PRESIDENT -> GENERAL(학번 순) 입니다.

## Screenshot

- 등록
<img width="480" alt="스크린샷 2024-12-27 오후 3 04 07" src="https://github.com/user-attachments/assets/afe54ddf-bd80-428c-9c4d-c1102e585532" />

- 조회
<img width="619" alt="스크린샷 2024-12-27 오후 4 43 56" src="https://github.com/user-attachments/assets/55ec8359-b759-469d-8346-c251cfa3a966" />

- 수정 후 조회
<img width="1258" alt="스크린샷 2024-12-28 오후 4 00 04" src="https://github.com/user-attachments/assets/e92de8f9-0f4f-436c-9a49-051bdcfb33b3" />

- 삭제 후 조회
<img width="809" alt="스크린샷 2024-12-28 오후 4 26 55" src="https://github.com/user-attachments/assets/08b15fa1-cd44-42b9-905c-36520e3695e4" />

- 사진 등록
<img width="883" alt="스크린샷 2024-12-27 오후 3 06 33" src="https://github.com/user-attachments/assets/201adf9b-85f2-4596-9738-cde939997926" />

2024-12-28 10:07 UTC, limehee requested changes
회장, 부회장, 운영진 등의 정보를 관리하기 위해 이전에 `position` 테이블을 생성한 적이 있어요. 이번에 작성된 부분과 일부 겹치는 내용이 있어, 두 도메인 중 하나를 삭제하고 통합하는 것이 더 효율적일 것 같아요.

2024-12-28 10:07 UTC, limehee commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +            "assignments", "submits", "executives")
`isUserAccessibleByCategory()` 메서드에서 비로그인 사용자도 `executives` 경로에 접근할 수 있도록 허용하고 있지만, 현재 `roleCategoryMap`에는 운영진 이상의 권한만 허용되어 있어요. `GUEST`, `USER` 권한을 가진 사용자도 운영진 사진을 열람할 수 있도록 수정이 필요해요.

2024-12-29 09:07 UTC, SongJaeHoonn commented
@limehee 
> 회장, 부회장, 운영진 등의 정보를 관리하기 위해 이전에 `position` 테이블을 생성한 적이 있어요. 이번에 작성된 부분과 일부 겹치는 내용이 있어, 두 도메인 중 하나를 삭제하고 통합하는 것이 더 효율적일 것 같아요.

Position 테이블이 멤버의 직책을 담당하는 것이라고 알고 있었는데, 직책 중 일반 회원, 코어팀도 포함되어 있어 운영진 정보만(회장, 부회장, 운영진) 관리하는 테이블을 하나 더 만들도록 했었습니다.

그런데 다시 보니 겹치는 부분이 상당히 많고, 직책 등록이 더욱 포괄적인 것 같아 `Executive`도메인을 삭제하고, `Position`도메인으로 운영진을 관리할 수 있는 로직을 옮기는 방식이 더 좋을 것 같습니다! 감사합니다. 작업 후 다시 리뷰 요청 드리겠습니다.

2024-12-30 02:10 UTC, mingmingmon requested changes

2024-12-30 13:38 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/memberManagement/executive/adapter/out/persistence/ExecutiveJpaEntity.java
> +    private Boolean isDeleted;
`deletedAt`을 추가함으로써 삭제된지 오래된 데이터들을 영구 삭제하거나, 혹시라도 복구할 때 삭제 시점을 보고 복구하기 위함인가요??
`boardEmoji`를 제외한 다른 도메인들에는 `deletedAt`이 없어서 질문드립니다!
`deletedAt`을 추가하는 도메인에 대한 특이사항이 있을까요?

2024-12-30 14:08 UTC, SongJaeHoonn commented
@limehee 

Executive 도메인을 삭제하고 Position에 운영진 정보를 등록하고 조회하는 로직을 추가하려고 했으나, 
현재 기획하고 구현한 운영진 관리 로직에는 직책 정보만이 아닌 이름, 프로필 사진, 이메일, 관심 분야 등이 있습니다. 

`Position` 도메인 내에서 `Member`를 외부에서 불러와 운영진 정보를 조회시킬 순 있겠으나, 멤버스 계정에 사용하는 정보와 랜딩페이지에 노출시키고 싶은 정보는 다를 수 있으므로 `Executive` 테이블을 유지하는 것이 좋다고 생각했습니다. 그렇지만 `Position` 도메인 내에서 직급 정보를 관리한다고 `Executive`를 전부 `Position` 내부에 추가한다는 것은 한 도메인에서 두 책임을 한꺼번에 관리하는 것이라고 생각합니다.

그 이유는, `Position`은 직책에 관련된 책임만 가지고 `Executive`는 운영진 정보에 대한 책임을 가지기 때문입니다.

따라서, `Executive` 테이블 내에 `Position`정보를 포함하기로 결정해보았습니다.
운영진 조회시, external에서  `Position`정보를 가져와 조회할 수 있도록 구현했습니다.

검토해주시면 감사하겠습니다!!

2024-12-30 15:44 UTC, limehee commented on src/main/java/page/clab/api/domain/memberManagement/executive/adapter/out/persistence/ExecutiveJpaEntity.java
> +    private Boolean isDeleted;
저는 현재로서는 `updatedAt` 필드만으로도 삭제 시점을 충분히 관리할 수 있다고 생각해요. 다만, `deletedAt` 필드를 추가하게 된다면, 다른 소프트 삭제를 사용하는 테이블에도 동일하게 적용하여 일관성을 유지하는 것이 적절하다고 판단돼요.

2024-12-31 07:29 UTC, limehee reviewed
운영진의 기존 서비스 가입 정보를 배제하고 새로 입력받아 랜딩 페이지에 게시하려는 것으로 이해했는데, 제가 해석한 내용이 맞는지 확인 부탁드려요.

랜딩 페이지에 게시되는 정보는 프로필 사진 정도만 변경되고, 학번, 이름, 이메일, 관심 분야 등 나머지 정보는 기존 가입 정보와 동일하게 유지되는 것이 더 적절하지 않을까 싶어요.

2024-12-31 07:29 UTC, limehee commented on src/main/java/page/clab/api/domain/memberManagement/executive/application/service/ExecutiveRetrievalService.java
> +    );
Enum 상수 값을 외부에서 하드코딩하여 사용하는 방식은 변경 사항이 생겼을 때 문제를 일으킬 가능성이 있어요. 예를 들어, `ExecutivePosition`에 새로운 값이 추가되거나 기존 값이 변경되었을 때, `PRIORITY`와 같은 별도의 맵을 수정하지 않으면 데이터 불일치로 인해 의도하지 않은 동작이 발생할 수 있어요.

대안으로, Enum 내부에 우선순위 정보를 포함시키는 방식을 제안해요.

### 제안

```java
package page.clab.api.domain.memberManagement.executive.domain;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ExecutivePosition {

    PRESIDENT("PRESIDENT", "회장", 1),
    VICE_PRESIDENT("VICE_PRESIDENT", "부회장", 2),
    GENERAL("GENERAL", "일반 운영진", 3);

    private final String key;
    private final String description;
    private final int priority;

    public static int getPriorityByKey(String key) {
        for (ExecutivePosition position : values()) {
            if (position.getKey().equals(key)) {
                return position.getPriority();
            }
        }
        throw new IllegalArgumentException("Invalid ExecutivePosition key: " + key);
    }
}
```

2024-12-31 13:19 UTC, SongJaeHoonn commented
> 운영진의 기존 서비스 가입 정보를 배제하고 새로 입력받아 랜딩 페이지에 게시하려는 것으로 이해했는데, 제가 해석한 내용이 맞는지 확인 부탁드려요.
> 
> 랜딩 페이지에 게시되는 정보는 프로필 사진 정도만 변경되고, 학번, 이름, 이메일, 관심 분야 등 나머지 정보는 기존 가입 정보와 동일하게 유지되는 것이 더 적절하지 않을까 싶어요.

일단, 현재 랜딩페이지에서 관리되고 있는 운영진 정보는 클라이언트에서 관리되고 있습니다. 운영진 정보를 받을 때, 운영진들에게 프로필 사진과 이메일 등을 전달받는 것으로 알고 있었습니다. 
기존에 정보를 받아 클라이언트에 저장해두는 방식을 서버에 저장해두는 방식으로 생각했습니다.(클라이언트 저장 -> 서버 저장)

또한 운영진 관리 기능을 구현할 때, 기존 가입 정보와 운영진 정보를 일치시키는 것을 생각하고 있긴 했습니다. 물론 이름이나 학번과 같은 경우에는 달라질 일이 없지만, 공공연하게 보여지는 이메일을 바꾸거나 관심분야를 다르게 설정할 수도 있지 않을까 싶어 함께 묶어 등록할 수 있도록 구현해 둔 것이었습니다. 이러한 이유로 `Executive`도메인을 남겨두게 되었습니다.(책임 분리를 위해 `Executive`테이블은 필요하다고 생각합니다)
이름과 학번같은 변경되지 않는 요소들은 `Member`도메인에서 가져와도 될 것 같긴 합니다!

2024-12-31 13:22 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/memberManagement/executive/application/service/ExecutiveRetrievalService.java
> +    );
`enum`이 수정이 되면 Map도 바뀌어야 하는데 일일이 찾아서 바꾸기 어렵겠네요,, 좋은 지적 감사합니다!

다만 `ExecutivePosition`은 삭제하고 `PositionType`을 사용하고 있어서, 방법 강구해서 수정해보도록 하겠습니다.

2024-12-31 16:41 UTC, limehee commented
> 또한 운영진 관리 기능을 구현할 때, 기존 가입 정보와 운영진 정보를 일치시키는 것을 생각하고 있긴 했습니다. 물론 이름이나 학번과 같은 경우에는 달라질 일이 없지만, 공공연하게 보여지는 이메일을 바꾸거나 관심분야를 다르게 설정할 수도 있지 않을까 싶어 함께 묶어 등록할 수 있도록 구현해 둔 것이었습니다. 이러한 이유로 `Executive`도메인을 남겨두게 되었습니다.(책임 분리를 위해 `Executive`테이블은 필요하다고 생각합니다) 이름과 학번같은 변경되지 않는 요소들은 `Member`도메인에서 가져와도 될 것 같긴 합니다!

해당 부분은 운영진 분들과도 논의해보는게 좋을 것 같아요. 실제로 이 기능을 이용하는 사용자가 운영진이니까요.

2025-01-01 19:44 UTC, limehee commented on src/main/java/page/clab/api/domain/memberManagement/executive/application/dto/request/ExecutiveRequestDto.java
> +    @Schema(description = "이메일", example = "clab.coreteam@gamil.com")
@SongJaeHoonn 오탈자 수정 부탁드려요

2025-01-01 19:51 UTC, limehee approved these changes
코파일럿에서 지적한 이메일 오탈자만 수정되면, 추가적으로 수정할 부분은 없을 것 같습니다.

2025-01-02 07:58 UTC, mingmingmon approved these changes

2025-01-03 06:26 UTC, limehee approved these changes

2025-01-04 11:02 UTC, merged